-- Operator-owned catalog controls. These commands do not change player
-- balances and remain separately audited by the application boundary.
CREATE OR REPLACE FUNCTION public.game_catalog_operator(p_actor uuid) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,pg_temp AS $$ BEGIN IF NOT EXISTS(SELECT 1 FROM public.user_roles WHERE user_id=p_actor AND role='operator'::public.admin_role) THEN RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='operator role required'; END IF; END $$;
CREATE OR REPLACE FUNCTION public.business_admin_list(p_actor uuid) RETURNS TABLE(id uuid,symbol text,name text,description text,purchase_cost bigint,daily_revenue bigint,daily_operating_cost bigint,active boolean) LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,pg_temp AS $$ BEGIN PERFORM public.game_catalog_operator(p_actor); RETURN QUERY SELECT business.id,business.symbol,business.name,business.description,business.purchase_cost,business.daily_revenue,business.daily_operating_cost,business.active FROM public.virtual_business_types AS business ORDER BY business.active DESC,business.purchase_cost,business.symbol; END $$;
CREATE OR REPLACE FUNCTION public.business_admin_update(p_actor uuid,p_id uuid,p_name text,p_description text,p_active boolean) RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,pg_temp AS $$ BEGIN PERFORM public.game_catalog_operator(p_actor); UPDATE public.virtual_business_types SET name=coalesce(nullif(btrim(p_name),''),name),description=coalesce(p_description,description),active=coalesce(p_active,active),updated_at=clock_timestamp() WHERE id=p_id; RETURN FOUND; END $$;
CREATE OR REPLACE FUNCTION public.season_event_admin_list(p_actor uuid) RETURNS TABLE(id uuid,season_name text,title text,description text,cost_wld bigint,points_per_entry integer,active boolean,ends_at timestamptz) LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,pg_temp AS $$ BEGIN PERFORM public.game_catalog_operator(p_actor); RETURN QUERY SELECT event.id,season.name,event.title,event.description,event.cost_wld,event.points_per_entry,event.active,season.ends_at FROM public.virtual_consumption_events AS event JOIN public.virtual_seasons AS season ON season.id=event.season_id ORDER BY event.active DESC,event.created_at DESC; END $$;
CREATE OR REPLACE FUNCTION public.season_event_admin_create(p_actor uuid,p_title text,p_description text,p_cost bigint,p_points integer) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,pg_temp AS $$ DECLARE v_season uuid;v_id uuid; BEGIN PERFORM public.game_catalog_operator(p_actor); IF nullif(btrim(p_title),'') IS NULL OR char_length(p_title)>100 OR char_length(coalesce(p_description,''))>500 OR p_cost<1 OR p_cost>100000 OR p_points<1 OR p_points>10000 THEN RAISE EXCEPTION USING ERRCODE='22023',MESSAGE='invalid event'; END IF; SELECT id INTO v_season FROM public.virtual_seasons WHERE active AND starts_at<=clock_timestamp() AND ends_at>clock_timestamp() FOR KEY SHARE; IF v_season IS NULL THEN RAISE EXCEPTION USING ERRCODE='22023',MESSAGE='active season required'; END IF; INSERT INTO public.virtual_consumption_events(season_id,title,description,cost_wld,points_per_entry) VALUES(v_season,btrim(p_title),coalesce(p_description,''),p_cost,p_points) RETURNING id INTO v_id; RETURN v_id; END $$;
CREATE OR REPLACE FUNCTION public.season_event_admin_update(p_actor uuid,p_id uuid,p_title text,p_description text,p_active boolean) RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,pg_temp AS $$ BEGIN PERFORM public.game_catalog_operator(p_actor); UPDATE public.virtual_consumption_events SET title=coalesce(nullif(btrim(p_title),''),title),description=coalesce(p_description,description),active=coalesce(p_active,active) WHERE id=p_id; RETURN FOUND; END $$;
ALTER FUNCTION public.game_catalog_operator(uuid) OWNER TO moneyverse_migrator; ALTER FUNCTION public.business_admin_list(uuid) OWNER TO moneyverse_migrator; ALTER FUNCTION public.business_admin_update(uuid,uuid,text,text,boolean) OWNER TO moneyverse_migrator; ALTER FUNCTION public.season_event_admin_list(uuid) OWNER TO moneyverse_migrator; ALTER FUNCTION public.season_event_admin_create(uuid,text,text,bigint,integer) OWNER TO moneyverse_migrator; ALTER FUNCTION public.season_event_admin_update(uuid,uuid,text,text,boolean) OWNER TO moneyverse_migrator;
REVOKE ALL ON FUNCTION public.game_catalog_operator(uuid),public.business_admin_list(uuid),public.business_admin_update(uuid,uuid,text,text,boolean),public.season_event_admin_list(uuid),public.season_event_admin_create(uuid,text,text,bigint,integer),public.season_event_admin_update(uuid,uuid,text,text,boolean) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.business_admin_list(uuid),public.business_admin_update(uuid,uuid,text,text,boolean),public.season_event_admin_list(uuid),public.season_event_admin_create(uuid,text,text,bigint,integer),public.season_event_admin_update(uuid,uuid,text,text,boolean) TO moneyverse_app;
