BEGIN;
INSERT INTO public.shop_catalog(code,name,description,category,base_price,effect_kind,purchase_limit) VALUES
('work_gloves','초보 작업 장갑','작업 품질 보호용 장갑입니다.','general',150,'convenience','once'),('toolbox','기본 공구함','기술 작업용 기본 공구함입니다.','general',250,'convenience','account_one'),('work_bag','작은 작업 가방','작업 준비 공간을 늘립니다.','general',300,'convenience','account_one'),('energy_drink','작업 에너지 음료','쉬운 작업 재도전용 소모품입니다.','general',40,'convenience','daily_2'),('bus_ticket','버스 이용권','배달 대기용 소모품입니다.','general',50,'convenience','daily_3'),('repair_kit','도구 수리 키트','도구 수리용 소모품입니다.','general',80,'convenience','unlimited'),('work_insurance','작업 실패 보험','작업 재료비 보호용 소모품입니다.','general',100,'convenience','daily_1'),('profile_tag','프로필 이름표','프로필 장식입니다.','general',200,'decoration','permanent'),('business_license','초보 사업 허가증','초보 사업용 허가증입니다.','general',500,'convenience','level_5'),('stall_crate','노점 재고 상자','노점 운영용 소모품입니다.','general',150,'convenience','business_owned'),
('farm_tool','개량 농기구','농업 작업용 도구입니다.','job',1200,'convenience','account_one'),('soil_analyzer','토양 분석기','농업 계약용 장비입니다.','job',2500,'convenience','account_one'),('pickaxe','강화 곡괭이','광업 작업용 도구입니다.','job',1400,'convenience','account_one'),('ore_detector','광물 탐지기','조사 계약용 장비입니다.','job',3000,'convenience','account_one'),('delivery_bag','대형 배달 가방','운송 계약용 장비입니다.','job',1300,'convenience','account_one'),('cargo_bike','소형 화물 자전거','운송 편의 장비입니다.','job',4000,'convenience','account_one'),('precision_tools','정밀 공구 세트','기술 작업용 장비입니다.','job',1600,'convenience','account_one'),('diagnostics','진단 장비','시설 점검용 장비입니다.','job',3500,'convenience','account_one'),('terminal','휴대용 단말기','상인 작업용 장비입니다.','job',1500,'convenience','account_one'),('market_pass','시장 분석권','NPC 주문 정보용 이용권입니다.','job',500,'convenience','weekly_1'),
('display_stand','기본 진열대','판매대용 진열대입니다.','business',1000,'convenience','once'),('business_stock','사업 재고 묶음','하루 운영에 쓰는 재고입니다.','business',300,'convenience','unlimited'),('local_ad','지역 광고','다음 정산용 광고입니다.','business',500,'convenience','weekly_2'),('facility_service','시설 정비','시설 효율을 회복합니다.','business',700,'convenience','state_based'),('warehouse_upgrade','창고 확장','재고 용량을 확장합니다.','business',3000,'convenience','stage_based'),('delivery_contract','배달 계약','운송 정산용 계약입니다.','business',1200,'convenience','timed'),('staff_training','직원 교육','운영비 관리 교육입니다.','business',2500,'convenience','stage_based'),('business_insurance','사업 보험','사업 사건 손실을 완화합니다.','business',1000,'convenience','timed'),('medium_license','중형 사업 허가증','중형 사업 구매 조건입니다.','business',5000,'convenience','once'),('advanced_license','고급 사업 허가증','고급 사업 구매 조건입니다.','business',15000,'convenience','once'),
('used_bicycle','중고 자전거','배달 작업용 이동수단입니다.','vehicle',5000,'convenience','account_one'),('scooter','소형 스쿠터','고급 운송 작업용 이동수단입니다.','vehicle',15000,'convenience','account_one'),('cargo_van','소형 화물차','사업 물류용 이동수단입니다.','vehicle',45000,'convenience','account_one'),('personal_storage','개인 창고','사업 재고 한도를 늘립니다.','vehicle',20000,'convenience','account_one'),('workshop_lease','작업실 임대권','기술 계약용 임대권입니다.','vehicle',35000,'convenience','timed'),('office_lease','사무실 임대권','중형 사업 확장용 임대권입니다.','vehicle',80000,'convenience','timed'),
('season_frame','시즌 프로필 테두리','시즌 장식품입니다.','season',2000,'decoration','permanent'),('master_tag','직업 마스터 명찰','직업 조건 장식품입니다.','season',5000,'decoration','state_based'),('digital_poster','한정 디지털 포스터','시즌 수집품입니다.','season',8000,'display','limited'),('watch_icon','명품 시계 아이콘','프로필 장식품입니다.','luxury',25000,'decoration','permanent'),('vehicle_skin','한정 차량 스킨','이동수단 장식품입니다.','luxury',40000,'decoration','limited'),('business_sign','사업 브랜드 간판','사업 페이지 장식품입니다.','luxury',50000,'decoration','limited'),('season_sculpture','시즌 기념 조형물','후반 수집품입니다.','season',100000,'display','limited')
ON CONFLICT(code) DO NOTHING;
INSERT INTO public.shop_inventory(catalog_id,quantity,restock_rule) SELECT id,NULL,'continuous' FROM public.shop_catalog ON CONFLICT(catalog_id) DO NOTHING;
COMMIT;
