-- A profile image a member uploads, and the gate that decides who may see it.
--
-- 080 gave `member_profiles.image_url` and the form asks for an address,
-- which it says out loud is a stand-in: "아직 이미지를 직접 올리는" is in the
-- field's own description. The bytes had nowhere to go, because the only
-- upload route in this application is the gallery's and it is the operator's.
--
-- WHY THIS IS NOT `/media/:key`. That route answers for published gallery
-- photos: `isPublicStorageKey` asks whether the key belongs to a photo an
-- operator has published, which is what keeps an unreviewed upload
-- unreachable. Serving a profile image through it would mean registering
-- every member's picture as a published gallery photo -- putting it in the
-- gallery, and making it public to anybody with the key regardless of what
-- the member chose. So a profile image gets its own gate, and that gate is
-- the profile's own visibility: a member who has set their image to
-- 'private' must not have it served to somebody who guessed the address.
--
-- WHY NO NEW COLUMN. The uploaded image is recorded as `image_url`, the same
-- column an address goes in, holding the path this deployment serves it from.
-- A second column naming the storage key would be the same fact written
-- twice, and `member_update_profile` replaces `image_url` wholesale -- so the
-- day a member typed an address over an upload, the two would disagree and
-- the row would point at a file nothing rendered. One column cannot disagree
-- with itself. The cost is that changing the address through the form leaves
-- the old file on disk; the upload path deletes what it replaces, and what
-- the form orphans is bytes nobody can reach, which is a sweep and not a
-- correctness problem.

BEGIN;

-- The one prefix, so the gate and the writer cannot drift apart. A key is
-- `<uuid>.<png|jpg|webp>`, generated by the server and never by a caller.
CREATE OR REPLACE FUNCTION public.member_profile_image_path(p_key text)
RETURNS text
LANGUAGE sql
IMMUTABLE
SET search_path = pg_catalog, pg_temp
AS $$
  SELECT CASE
    WHEN p_key ~ '^[0-9a-f-]{36}\.(png|jpg|webp)$' THEN '/media/profile/' || p_key
  END
$$;

-- May this viewer be served these bytes?
--
-- Deliberately one boolean and not a reason: the caller is a route that has
-- to answer the same 404 for "no such key", "not a profile image" and "not
-- yours to see", because distinguishing them confirms that a member has an
-- image they chose not to show.
CREATE OR REPLACE FUNCTION public.member_profile_image_visible(p_viewer uuid, p_key text)
RETURNS boolean
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, pg_temp
AS $$
DECLARE
  v_path text := public.member_profile_image_path(p_key);
  v_owner uuid;
  v_visibility public.profile_visibility;
  v_fields jsonb;
  v_is_member boolean;
BEGIN
  IF v_path IS NULL THEN
    RETURN false;
  END IF;

  SELECT profile_row.user_id, profile_row.visibility, profile_row.field_visibility
  INTO v_owner, v_visibility, v_fields
  FROM public.member_profiles AS profile_row
  JOIN public.users AS user_row ON user_row.id = profile_row.user_id
  WHERE profile_row.image_url = v_path
    AND user_row.status = 'active'::public.user_status;

  IF v_owner IS NULL THEN
    RETURN false;
  END IF;

  v_is_member := p_viewer IS NOT NULL AND EXISTS (
    SELECT 1 FROM public.users AS user_row
    WHERE user_row.id = p_viewer AND user_row.status = 'active'::public.user_status
  );

  -- Both gates, the way `member_profile_view` reads them: a profile withheld
  -- entirely withholds its picture too, whatever the field says.
  RETURN public.member_field_visible(
           v_visibility, v_fields, 'profile', p_viewer = v_owner, v_is_member)
     AND public.member_field_visible(
           v_visibility, v_fields, 'imageUrl', p_viewer = v_owner, v_is_member);
END;
$$;

-- Points the member's profile at bytes that have just been stored, and hands
-- back whatever it replaced so the caller can delete that file. The delete is
-- the caller's because this function must not know about a filesystem.
CREATE OR REPLACE FUNCTION public.member_set_profile_image(p_actor uuid, p_key text)
RETURNS TABLE(image_path text, replaced_key text)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, pg_temp
AS $$
DECLARE
  v_path text := public.member_profile_image_path(p_key);
  v_previous text;
BEGIN
  IF p_actor IS NULL OR NOT EXISTS (
    SELECT 1 FROM public.users AS user_row
    WHERE user_row.id = p_actor AND user_row.status = 'active'::public.user_status
  ) THEN
    RAISE EXCEPTION USING ERRCODE = '28000', MESSAGE = 'active user required';
  END IF;
  IF v_path IS NULL THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'invalid image storage key';
  END IF;

  SELECT profile_row.image_url INTO v_previous
  FROM public.member_profiles AS profile_row
  WHERE profile_row.user_id = p_actor
  FOR UPDATE;

  INSERT INTO public.member_profiles (user_id, image_url)
  VALUES (p_actor, v_path)
  ON CONFLICT (user_id) DO UPDATE
  SET image_url = excluded.image_url, updated_at = pg_catalog.clock_timestamp();

  image_path := v_path;
  -- Only an upload is worth deleting. An address the member typed points at
  -- somebody else's server and is not ours to remove.
  replaced_key := CASE
    WHEN v_previous LIKE '/media/profile/%' THEN substr(v_previous, 16)
  END;
  RETURN NEXT;
END;
$$;

CREATE OR REPLACE FUNCTION public.member_clear_profile_image(p_actor uuid)
RETURNS TABLE(replaced_key text)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, pg_temp
AS $$
DECLARE
  v_previous text;
BEGIN
  IF p_actor IS NULL OR NOT EXISTS (
    SELECT 1 FROM public.users AS user_row
    WHERE user_row.id = p_actor AND user_row.status = 'active'::public.user_status
  ) THEN
    RAISE EXCEPTION USING ERRCODE = '28000', MESSAGE = 'active user required';
  END IF;

  SELECT profile_row.image_url INTO v_previous
  FROM public.member_profiles AS profile_row
  WHERE profile_row.user_id = p_actor
  FOR UPDATE;

  UPDATE public.member_profiles AS profile_row
  SET image_url = NULL, updated_at = pg_catalog.clock_timestamp()
  WHERE profile_row.user_id = p_actor;

  replaced_key := CASE
    WHEN v_previous LIKE '/media/profile/%' THEN substr(v_previous, 16)
  END;
  RETURN NEXT;
END;
$$;

-- Every key a profile still points at. The upload path deletes what it
-- replaces, but a member who types an address over an upload orphans the file
-- it was using, so something has to be able to answer "is anybody still
-- pointing at this" without reading `member_profiles` directly.
CREATE OR REPLACE FUNCTION public.member_profile_image_keys()
RETURNS SETOF text
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, pg_temp
AS $$
  SELECT substr(profile_row.image_url, 16)
  FROM public.member_profiles AS profile_row
  WHERE profile_row.image_url LIKE '/media/profile/%'
$$;

ALTER FUNCTION public.member_profile_image_path(text) OWNER TO moneyverse_migrator;
ALTER FUNCTION public.member_profile_image_visible(uuid, text) OWNER TO moneyverse_migrator;
ALTER FUNCTION public.member_set_profile_image(uuid, text) OWNER TO moneyverse_migrator;
ALTER FUNCTION public.member_clear_profile_image(uuid) OWNER TO moneyverse_migrator;
ALTER FUNCTION public.member_profile_image_keys() OWNER TO moneyverse_migrator;

REVOKE ALL PRIVILEGES ON FUNCTION public.member_profile_image_path(text) FROM PUBLIC, moneyverse_app;
REVOKE ALL PRIVILEGES ON FUNCTION public.member_profile_image_visible(uuid, text) FROM PUBLIC, moneyverse_app;
REVOKE ALL PRIVILEGES ON FUNCTION public.member_set_profile_image(uuid, text) FROM PUBLIC, moneyverse_app;
REVOKE ALL PRIVILEGES ON FUNCTION public.member_clear_profile_image(uuid) FROM PUBLIC, moneyverse_app;
REVOKE ALL PRIVILEGES ON FUNCTION public.member_profile_image_keys() FROM PUBLIC, moneyverse_app;

GRANT EXECUTE ON FUNCTION public.member_profile_image_visible(uuid, text) TO moneyverse_app;
GRANT EXECUTE ON FUNCTION public.member_set_profile_image(uuid, text) TO moneyverse_app;
GRANT EXECUTE ON FUNCTION public.member_clear_profile_image(uuid) TO moneyverse_app;
GRANT EXECUTE ON FUNCTION public.member_profile_image_keys() TO moneyverse_app;

COMMIT;
