-- One-time recovery codes for an administrator who has lost the enrolled
-- TOTP device. Codes are generated by the application and only SHA-256
-- hashes reach this table. Issuing codes requires an already-open console,
-- recent OAuth reauthentication and a recent TOTP verification. Consuming a
-- code requires recent OAuth reauthentication and rotates directly into one
-- console session; it does not satisfy the TOTP step-up used by high-risk
-- writes.

CREATE TABLE IF NOT EXISTS public.admin_recovery_codes (
  id uuid PRIMARY KEY DEFAULT pg_catalog.gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES public.users(id),
  code_hash text NOT NULL CHECK (code_hash ~ '^[0-9a-f]{64}$'),
  created_at timestamptz NOT NULL DEFAULT pg_catalog.clock_timestamp(),
  expires_at timestamptz NOT NULL,
  consumed_at timestamptz,
  UNIQUE (user_id, code_hash)
);

CREATE TABLE IF NOT EXISTS public.admin_recovery_code_state (
  user_id uuid PRIMARY KEY REFERENCES public.users(id),
  failed_attempts integer NOT NULL DEFAULT 0 CHECK (failed_attempts >= 0),
  locked_until timestamptz
);

REVOKE ALL PRIVILEGES ON TABLE public.admin_recovery_codes FROM PUBLIC, moneyverse_app;
REVOKE ALL PRIVILEGES ON TABLE public.admin_recovery_code_state FROM PUBLIC, moneyverse_app;

CREATE OR REPLACE FUNCTION public.admin_recovery_codes_issue(
  p_actor uuid,
  p_session_id uuid,
  p_code_hashes text[]
)
RETURNS TABLE(code_count integer, expires_at timestamptz)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, pg_temp
AS $$
DECLARE
  v_now timestamptz := pg_catalog.clock_timestamp();
  v_expires timestamptz := v_now + pg_catalog.make_interval(days => 90);
  v_hash text;
BEGIN
  PERFORM public.admin_require_superadmin(p_actor);
  IF coalesce(pg_catalog.array_length(p_code_hashes, 1), 0) <> 8
     OR EXISTS (SELECT 1 FROM pg_catalog.unnest(p_code_hashes) h WHERE h !~ '^[0-9a-f]{64}$')
     OR (SELECT pg_catalog.count(DISTINCT h) FROM pg_catalog.unnest(p_code_hashes) h) <> 8 THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'eight distinct recovery code hashes are required';
  END IF;
  IF NOT public.auth_session_has_recent_reauthentication(p_session_id, 300) THEN
    RAISE EXCEPTION USING ERRCODE = '42501', MESSAGE = 'recent reauthentication required';
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM public.auth_sessions s
    WHERE s.id = p_session_id AND s.user_id = p_actor AND s.revoked_at IS NULL
      AND s.expires_at > v_now AND s.admin_opened_at IS NOT NULL
      AND s.admin_closed_at IS NULL AND s.admin_last_seen_at >= v_now - interval '10 minutes'
  ) THEN
    RAISE EXCEPTION USING ERRCODE = '42501', MESSAGE = 'open administrator session required';
  END IF;
  IF NOT public.admin_second_factor_satisfied(p_actor, 120) THEN
    RAISE EXCEPTION USING ERRCODE = '42501', MESSAGE = 'recent second factor required';
  END IF;

  UPDATE public.admin_recovery_codes AS recovery_row SET expires_at = v_now
  WHERE recovery_row.user_id = p_actor AND recovery_row.consumed_at IS NULL
    AND recovery_row.expires_at > v_now;
  FOREACH v_hash IN ARRAY p_code_hashes LOOP
    INSERT INTO public.admin_recovery_codes(user_id, code_hash, expires_at)
    VALUES (p_actor, v_hash, v_expires);
  END LOOP;
  INSERT INTO public.admin_recovery_code_state(user_id, failed_attempts, locked_until)
  VALUES (p_actor, 0, NULL)
  ON CONFLICT (user_id) DO UPDATE SET failed_attempts = 0, locked_until = NULL;

  PERFORM public.admin_append_audit_event(
    p_actor, 'admin.recovery_codes.issued', p_actor, NULL,
    pg_catalog.jsonb_build_object('count', 8, 'expiresAt', v_expires)
  );
  RETURN QUERY SELECT 8, v_expires;
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_recovery_code_open_session(
  p_session_id uuid,
  p_actor uuid,
  p_code_hash text,
  p_token_hash text,
  p_csrf_hash text
)
RETURNS TABLE(accepted boolean, session_id uuid, expires_at timestamptz, idle_expires_at timestamptz)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, pg_temp
AS $$
DECLARE
  v_now timestamptz := pg_catalog.clock_timestamp();
  v_current public.auth_sessions%ROWTYPE;
  v_new uuid;
  v_state public.admin_recovery_code_state%ROWTYPE;
BEGIN
  PERFORM public.admin_require_superadmin(p_actor);
  IF p_code_hash !~ '^[0-9a-f]{64}$'
     OR coalesce(pg_catalog.char_length(p_token_hash), 0) < 32
     OR coalesce(pg_catalog.char_length(p_csrf_hash), 0) < 32 THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'invalid recovery request';
  END IF;
  SELECT * INTO v_current FROM public.auth_sessions s
  WHERE s.id = p_session_id AND s.user_id = p_actor AND s.revoked_at IS NULL
    AND s.expires_at > v_now FOR UPDATE;
  IF NOT FOUND OR NOT public.auth_session_has_recent_reauthentication(p_session_id, 300) THEN
    RAISE EXCEPTION USING ERRCODE = '42501', MESSAGE = 'recent reauthentication required';
  END IF;

  SELECT * INTO v_state FROM public.admin_recovery_code_state s
  WHERE s.user_id = p_actor FOR UPDATE;
  IF FOUND AND v_state.locked_until IS NOT NULL AND v_state.locked_until > v_now THEN
    PERFORM public.admin_append_audit_event(
      p_actor, 'admin.recovery_code.failed', p_actor, NULL,
      pg_catalog.jsonb_build_object('outcome', 'locked')
    );
    RETURN QUERY SELECT false, NULL::uuid, NULL::timestamptz, v_state.locked_until;
    RETURN;
  END IF;

  UPDATE public.admin_recovery_codes c SET consumed_at = v_now
  WHERE c.user_id = p_actor AND c.code_hash = p_code_hash
    AND c.consumed_at IS NULL AND c.expires_at > v_now;
  IF NOT FOUND THEN
    INSERT INTO public.admin_recovery_code_state(user_id, failed_attempts, locked_until)
    VALUES (p_actor, 1, NULL)
    ON CONFLICT (user_id) DO UPDATE
      SET failed_attempts = public.admin_recovery_code_state.failed_attempts + 1,
          locked_until = CASE WHEN public.admin_recovery_code_state.failed_attempts + 1 >= 5
            THEN v_now + interval '15 minutes'
            ELSE public.admin_recovery_code_state.locked_until END;
    PERFORM public.admin_append_audit_event(
      p_actor, 'admin.recovery_code.failed', p_actor, NULL,
      pg_catalog.jsonb_build_object('outcome', 'rejected')
    );
    RETURN QUERY SELECT false, NULL::uuid, NULL::timestamptz, NULL::timestamptz;
    RETURN;
  END IF;

  INSERT INTO public.admin_recovery_code_state(user_id, failed_attempts, locked_until)
  VALUES (p_actor, 0, NULL)
  ON CONFLICT (user_id) DO UPDATE SET failed_attempts = 0, locked_until = NULL;
  INSERT INTO public.auth_sessions(
    id, token_hash, csrf_hash, user_id, expires_at, created_at,
    prelogin_consent_version_id, prelogin_age_confirmed, prelogin_consented_at,
    reauthenticated_at, admin_opened_at, admin_last_seen_at, admin_rotated_from
  ) VALUES (
    pg_catalog.gen_random_uuid(), p_token_hash, p_csrf_hash, p_actor,
    v_now + interval '30 minutes', v_now,
    v_current.prelogin_consent_version_id, v_current.prelogin_age_confirmed,
    v_current.prelogin_consented_at, v_current.reauthenticated_at, v_now, v_now, p_session_id
  ) RETURNING id INTO v_new;
  UPDATE public.auth_sessions SET revoked_at = v_now, admin_closed_at = v_now
  WHERE id = p_session_id;
  PERFORM public.admin_append_audit_event(
    p_actor, 'admin.recovery_code.consumed', v_new, NULL,
    pg_catalog.jsonb_build_object('credentialId', (
      SELECT id FROM public.admin_recovery_codes
      WHERE user_id = p_actor AND code_hash = p_code_hash AND consumed_at = v_now LIMIT 1
    ))
  );
  RETURN QUERY SELECT true, v_new, v_now + interval '30 minutes', v_now + interval '10 minutes';
END;
$$;

ALTER FUNCTION public.admin_recovery_codes_issue(uuid, uuid, text[]) OWNER TO moneyverse_migrator;
ALTER FUNCTION public.admin_recovery_code_open_session(uuid, uuid, text, text, text) OWNER TO moneyverse_migrator;
REVOKE ALL PRIVILEGES ON FUNCTION public.admin_recovery_codes_issue(uuid, uuid, text[]) FROM PUBLIC, moneyverse_app;
REVOKE ALL PRIVILEGES ON FUNCTION public.admin_recovery_code_open_session(uuid, uuid, text, text, text) FROM PUBLIC, moneyverse_app;
GRANT EXECUTE ON FUNCTION public.admin_recovery_codes_issue(uuid, uuid, text[]) TO moneyverse_app;
GRANT EXECUTE ON FUNCTION public.admin_recovery_code_open_session(uuid, uuid, text, text, text) TO moneyverse_app;
