export interface DividendStock {
  ticker: string;
  nameKo: string;
  nameEn: string;
  country: 'KR' | 'US';
  currency: 'KRW' | 'USD';
  dividendYield: number; // 배당수익률 (%)
  annualDividend: number; // 1주당 연간 배당금 (원 또는 달러)
  frequency: '월' | '분기' | '반기' | '연';
  exDividendDate: string; // 배당락일/기준월 (예: '3월, 6월, 9월, 12월' 또는 '매월')
  currentPrice: number; // 주가 기준
}

export const PSEO_DIVIDEND_STOCKS: DividendStock[] = [
  // 🇺🇸 미국 인기 배당주 & ETF 30종목
  {
    ticker: 'O',
    nameKo: '리얼티 인컴',
    nameEn: 'Realty Income Corp',
    country: 'US',
    currency: 'USD',
    dividendYield: 5.4,
    annualDividend: 3.16,
    frequency: '월',
    exDividendDate: '매월 말일',
    currentPrice: 58.5,
  },
  {
    ticker: 'SCHD',
    nameKo: '슈드 (슈왑 US 배당 ETF)',
    nameEn: 'Schwab US Dividend Equity ETF',
    country: 'US',
    currency: 'USD',
    dividendYield: 3.6,
    annualDividend: 2.82,
    frequency: '분기',
    exDividendDate: '3월, 6월, 9월, 12월',
    currentPrice: 78.4,
  },
  {
    ticker: 'JEPI',
    nameKo: '제피 (JP모건 프리미엄 인컴 ETF)',
    nameEn: 'JPMorgan Equity Premium Income ETF',
    country: 'US',
    currency: 'USD',
    dividendYield: 7.8,
    annualDividend: 4.45,
    frequency: '월',
    exDividendDate: '매월 1일',
    currentPrice: 57.0,
  },
  {
    ticker: 'JEPQ',
    nameKo: '제피큐 (JP모건 나스닥 프리미엄 인컴 ETF)',
    nameEn: 'JPMorgan Nasdaq Equity Premium Income ETF',
    country: 'US',
    currency: 'USD',
    dividendYield: 9.2,
    annualDividend: 5.10,
    frequency: '월',
    exDividendDate: '매월 1일',
    currentPrice: 55.4,
  },
  {
    ticker: 'KO',
    nameKo: '코카콜라',
    nameEn: 'The Coca-Cola Company',
    country: 'US',
    currency: 'USD',
    dividendYield: 3.1,
    annualDividend: 1.94,
    frequency: '분기',
    exDividendDate: '3월, 6월, 9월, 11월',
    currentPrice: 62.5,
  },
  {
    ticker: 'AAPL',
    nameKo: '애플',
    nameEn: 'Apple Inc.',
    country: 'US',
    currency: 'USD',
    dividendYield: 0.5,
    annualDividend: 1.00,
    frequency: '분기',
    exDividendDate: '2월, 5월, 8월, 11월',
    currentPrice: 220.0,
  },
  {
    ticker: 'MSFT',
    nameKo: '마이크로소프트',
    nameEn: 'Microsoft Corp.',
    country: 'US',
    currency: 'USD',
    dividendYield: 0.7,
    annualDividend: 3.00,
    frequency: '분기',
    exDividendDate: '2월, 5월, 8월, 11월',
    currentPrice: 425.0,
  },
  {
    ticker: 'NVDA',
    nameKo: '엔비디아',
    nameEn: 'NVIDIA Corp.',
    country: 'US',
    currency: 'USD',
    dividendYield: 0.1,
    annualDividend: 0.16,
    frequency: '분기',
    exDividendDate: '3월, 6월, 9월, 12월',
    currentPrice: 125.0,
  },
  {
    ticker: 'JNJ',
    nameKo: '존슨앤존슨',
    nameEn: 'Johnson & Johnson',
    country: 'US',
    currency: 'USD',
    dividendYield: 3.2,
    annualDividend: 4.96,
    frequency: '분기',
    exDividendDate: '2월, 5월, 8월, 11월',
    currentPrice: 155.0,
  },
  {
    ticker: 'PG',
    nameKo: '프록터 앤 갬블 (P&G)',
    nameEn: 'Procter & Gamble Co.',
    country: 'US',
    currency: 'USD',
    dividendYield: 2.4,
    annualDividend: 4.03,
    frequency: '분기',
    exDividendDate: '1월, 4월, 7월, 10월',
    currentPrice: 168.0,
  },
  {
    ticker: 'PEP',
    nameKo: '펩시코',
    nameEn: 'PepsiCo, Inc.',
    country: 'US',
    currency: 'USD',
    dividendYield: 3.2,
    annualDividend: 5.42,
    frequency: '분기',
    exDividendDate: '3월, 6월, 9월, 12월',
    currentPrice: 169.0,
  },
  {
    ticker: 'MCD',
    nameKo: '맥도날드',
    nameEn: "McDonald's Corp.",
    country: 'US',
    currency: 'USD',
    dividendYield: 2.3,
    annualDividend: 6.68,
    frequency: '분기',
    exDividendDate: '2월, 6월, 8월, 11월',
    currentPrice: 290.0,
  },
  {
    ticker: 'ABBV',
    nameKo: '애브비',
    nameEn: 'AbbVie Inc.',
    country: 'US',
    currency: 'USD',
    dividendYield: 3.4,
    annualDividend: 6.20,
    frequency: '분기',
    exDividendDate: '1월, 4월, 7월, 10월',
    currentPrice: 182.0,
  },
  {
    ticker: 'CVX',
    nameKo: '쉐브론',
    nameEn: 'Chevron Corp.',
    country: 'US',
    currency: 'USD',
    dividendYield: 4.3,
    annualDividend: 6.52,
    frequency: '분기',
    exDividendDate: '2월, 5월, 8월, 11월',
    currentPrice: 151.0,
  },
  {
    ticker: 'XOM',
    nameKo: '엑슨모빌',
    nameEn: 'Exxon Mobil Corp.',
    country: 'US',
    currency: 'USD',
    dividendYield: 3.3,
    annualDividend: 3.80,
    frequency: '분기',
    exDividendDate: '2월, 5월, 8월, 11월',
    currentPrice: 115.0,
  },
  {
    ticker: 'T',
    nameKo: 'AT&T',
    nameEn: 'AT&T Inc.',
    country: 'US',
    currency: 'USD',
    dividendYield: 5.2,
    annualDividend: 1.11,
    frequency: '분기',
    exDividendDate: '1월, 4월, 7월, 10월',
    currentPrice: 21.3,
  },
  {
    ticker: 'VZ',
    nameKo: '버라이즌',
    nameEn: 'Verizon Communications',
    country: 'US',
    currency: 'USD',
    dividendYield: 6.3,
    annualDividend: 2.67,
    frequency: '분기',
    exDividendDate: '1월, 4월, 7월, 10월',
    currentPrice: 42.4,
  },
  {
    ticker: 'MAIN',
    nameKo: '메인 스트리트 캐피털 (월배당)',
    nameEn: 'Main Street Capital Corp.',
    country: 'US',
    currency: 'USD',
    dividendYield: 6.8,
    annualDividend: 3.00,
    frequency: '월',
    exDividendDate: '매월 중순',
    currentPrice: 44.1,
  },
  {
    ticker: 'MO',
    nameKo: '알트리아 그룹 (고배당)',
    nameEn: 'Altria Group, Inc.',
    country: 'US',
    currency: 'USD',
    dividendYield: 8.1,
    annualDividend: 4.08,
    frequency: '분기',
    exDividendDate: '3월, 6월, 9월, 12월',
    currentPrice: 50.3,
  },
  {
    ticker: 'IBM',
    nameKo: 'IBM',
    nameEn: 'International Business Machines',
    country: 'US',
    currency: 'USD',
    dividendYield: 3.1,
    annualDividend: 6.68,
    frequency: '분기',
    exDividendDate: '2월, 5월, 8월, 11월',
    currentPrice: 215.0,
  },
  {
    ticker: 'WMT',
    nameKo: '월마트',
    nameEn: 'Walmart Inc.',
    country: 'US',
    currency: 'USD',
    dividendYield: 1.1,
    annualDividend: 0.83,
    frequency: '분기',
    exDividendDate: '3월, 5월, 8월, 12월',
    currentPrice: 75.5,
  },
  {
    ticker: 'COST',
    nameKo: '코스트코',
    nameEn: 'Costco Wholesale Corp.',
    country: 'US',
    currency: 'USD',
    dividendYield: 0.5,
    annualDividend: 4.64,
    frequency: '분기',
    exDividendDate: '2월, 5월, 8월, 11월',
    currentPrice: 928.0,
  },
  {
    ticker: 'SPY',
    nameKo: 'SPDR S&P 500 ETF',
    nameEn: 'SPDR S&P 500 ETF Trust',
    country: 'US',
    currency: 'USD',
    dividendYield: 1.2,
    annualDividend: 6.80,
    frequency: '분기',
    exDividendDate: '3월, 6월, 9월, 12월',
    currentPrice: 566.0,
  },
  {
    ticker: 'VOO',
    nameKo: '뱅가드 S&P 500 ETF',
    nameEn: 'Vanguard S&P 500 ETF',
    country: 'US',
    currency: 'USD',
    dividendYield: 1.3,
    annualDividend: 6.75,
    frequency: '분기',
    exDividendDate: '3월, 6월, 9월, 12월',
    currentPrice: 519.0,
  },
  {
    ticker: 'QQQ',
    nameKo: '인베스코 나스닥 100 ETF',
    nameEn: 'Invesco QQQ Trust',
    country: 'US',
    currency: 'USD',
    dividendYield: 0.6,
    annualDividend: 2.90,
    frequency: '분기',
    exDividendDate: '3월, 6월, 9월, 12월',
    currentPrice: 483.0,
  },

  // 🇰🇷 국내 우량 고배당주 30종목
  {
    ticker: '005930',
    nameKo: '삼성전자',
    nameEn: 'Samsung Electronics',
    country: 'KR',
    currency: 'KRW',
    dividendYield: 2.4,
    annualDividend: 1444,
    frequency: '분기',
    exDividendDate: '3월, 6월, 9월, 12월 말일',
    currentPrice: 60200,
  },
  {
    ticker: '005935',
    nameKo: '삼성전자우 (우선주)',
    nameEn: 'Samsung Electronics (Pref)',
    country: 'KR',
    currency: 'KRW',
    dividendYield: 2.8,
    annualDividend: 1445,
    frequency: '분기',
    exDividendDate: '3월, 6월, 9월, 12월 말일',
    currentPrice: 51600,
  },
  {
    ticker: '005380',
    nameKo: '현대자동차',
    nameEn: 'Hyundai Motor',
    country: 'KR',
    currency: 'KRW',
    dividendYield: 5.2,
    annualDividend: 12000,
    frequency: '분기',
    exDividendDate: '3월, 6월, 9월, 12월',
    currentPrice: 231000,
  },
  {
    ticker: '005387',
    nameKo: '현대차2우B (고배당 우선주)',
    nameEn: 'Hyundai Motor 2P (Pref)',
    country: 'KR',
    currency: 'KRW',
    dividendYield: 7.4,
    annualDividend: 12100,
    frequency: '분기',
    exDividendDate: '3월, 6월, 9월, 12월',
    currentPrice: 163500,
  },
  {
    ticker: '105560',
    nameKo: 'KB금융',
    nameEn: 'KB Financial Group',
    country: 'KR',
    currency: 'KRW',
    dividendYield: 4.8,
    annualDividend: 3800,
    frequency: '분기',
    exDividendDate: '3월, 6월, 9월, 12월',
    currentPrice: 79200,
  },
  {
    ticker: '055550',
    nameKo: '신한지주',
    nameEn: 'Shinhan Financial Group',
    country: 'KR',
    currency: 'KRW',
    dividendYield: 5.1,
    annualDividend: 2600,
    frequency: '분기',
    exDividendDate: '3월, 6월, 9월, 12월',
    currentPrice: 51000,
  },
  {
    ticker: '086790',
    nameKo: '하나금융지주',
    nameEn: 'Hana Financial Group',
    country: 'KR',
    currency: 'KRW',
    dividendYield: 5.6,
    annualDividend: 3400,
    frequency: '분기',
    exDividendDate: '3월, 6월, 9월, 12월',
    currentPrice: 60700,
  },
  {
    ticker: '316140',
    nameKo: '우리금융지주',
    nameEn: 'Woori Financial Group',
    country: 'KR',
    currency: 'KRW',
    dividendYield: 6.5,
    annualDividend: 1000,
    frequency: '분기',
    exDividendDate: '3월, 6월, 9월, 12월',
    currentPrice: 15380,
  },
  {
    ticker: '033780',
    nameKo: 'KT&G (케이티앤지)',
    nameEn: 'KT&G Corp.',
    country: 'KR',
    currency: 'KRW',
    dividendYield: 5.5,
    annualDividend: 5400,
    frequency: '반기',
    exDividendDate: '6월 말, 12월 말',
    currentPrice: 98200,
  },
  {
    ticker: '088980',
    nameKo: '맥쿼리인프라 (월배당 인프라 펀드)',
    nameEn: 'Macquarie Korea Infrastructure Fund',
    country: 'KR',
    currency: 'KRW',
    dividendYield: 6.8,
    annualDividend: 780,
    frequency: '반기',
    exDividendDate: '6월 말, 12월 말',
    currentPrice: 11470,
  },
  {
    ticker: '017670',
    nameKo: 'SK텔레콤',
    nameEn: 'SK Telecom',
    country: 'KR',
    currency: 'KRW',
    dividendYield: 6.0,
    annualDividend: 3320,
    frequency: '분기',
    exDividendDate: '3월, 6월, 9월, 12월',
    currentPrice: 55300,
  },
  {
    ticker: '030200',
    nameKo: 'KT',
    nameEn: 'KT Corp.',
    country: 'KR',
    currency: 'KRW',
    dividendYield: 5.0,
    annualDividend: 1960,
    frequency: '분기',
    exDividendDate: '3월, 6월, 9월, 12월',
    currentPrice: 39200,
  },
  {
    ticker: '005490',
    nameKo: 'POSCO홀딩스',
    nameEn: 'POSCO Holdings',
    country: 'KR',
    currency: 'KRW',
    dividendYield: 3.2,
    annualDividend: 10000,
    frequency: '분기',
    exDividendDate: '3월, 6월, 9월, 12월',
    currentPrice: 312500,
  },
  {
    ticker: '000660',
    nameKo: 'SK하이닉스',
    nameEn: 'SK Hynix',
    country: 'KR',
    currency: 'KRW',
    dividendYield: 0.8,
    annualDividend: 1500,
    frequency: '분기',
    exDividendDate: '3월, 6월, 9월, 12월',
    currentPrice: 187500,
  },
  {
    ticker: '000270',
    nameKo: '기아',
    nameEn: 'Kia Corp.',
    country: 'KR',
    currency: 'KRW',
    dividendYield: 5.4,
    annualDividend: 5600,
    frequency: '연',
    exDividendDate: '3월 정기주총일',
    currentPrice: 103700,
  },
  {
    ticker: '000810',
    nameKo: '삼성화재',
    nameEn: 'Samsung Fire & Marine Insurance',
    country: 'KR',
    currency: 'KRW',
    dividendYield: 4.5,
    annualDividend: 16000,
    frequency: '연',
    exDividendDate: '12월 말일',
    currentPrice: 355500,
  },
  {
    ticker: '032830',
    nameKo: '삼성생명',
    nameEn: 'Samsung Life Insurance',
    country: 'KR',
    currency: 'KRW',
    dividendYield: 4.1,
    annualDividend: 3700,
    frequency: '연',
    exDividendDate: '12월 말일',
    currentPrice: 90200,
  },
  {
    ticker: '010130',
    nameKo: '고려아연',
    nameEn: 'Korea Zinc',
    country: 'KR',
    currency: 'KRW',
    dividendYield: 2.8,
    annualDividend: 20000,
    frequency: '반기',
    exDividendDate: '6월 말, 12월 말',
    currentPrice: 714000,
  },
];

export function getDividendStockByTicker(ticker: string): DividendStock | undefined {
  return PSEO_DIVIDEND_STOCKS.find((s) => s.ticker.toLowerCase() === ticker.toLowerCase());
}
