export interface GlossaryTerm {
  slug: string;
  termKo: string;
  termEn: string;
  termJa: string;
  termZh: string;
  category: 'valuation' | 'profitability' | 'dividend' | 'tax' | 'trading' | 'macro';
  formula?: string;
  formulaDescriptionKo?: string;
  descriptionKo: string;
  descriptionEn: string;
  descriptionJa: string;
  descriptionZh: string;
  keyTakeawayKo: string;
  keyTakeawayEn: string;
  relatedCalculatorUrl?: string;
  relatedCalculatorLabelKo?: string;
  relatedTickers?: string[];
}

export const GLOSSARY_TERMS: GlossaryTerm[] = [
  {
    slug: 'per',
    termKo: 'PER (주가수익비율)',
    termEn: 'PER (Price to Earnings Ratio)',
    termJa: 'PER (株価収益率)',
    termZh: 'PER (市盈率)',
    category: 'valuation',
    formula: 'PER = 현재 주가 / 주당순이익(EPS)',
    formulaDescriptionKo: '기업이 벌어들이는 1주당 순이익 대비 주가가 몇 배로 거래되고 있는지를 나타내는 대표적인 밸류에이션 지표입니다.',
    descriptionKo: 'PER(Price to Earnings Ratio, 주가수익비율)은 기업의 주가가 주당순이익(EPS)의 몇 배인가를 나타내는 지표입니다. 수치가 낮을수록 기업의 이익 창출 능력에 비해 주가가 저평가되어 있음을 의미하며, 높을수록 미래 성장성에 대한 기대감이 주가에 반영되어 있음을 나타냅니다. 동종 업계 평균 PER과 비교하여 상대적 고평가/저평가 여부를 판단하는 것이 중요합니다.',
    descriptionEn: 'The Price to Earnings Ratio (PER / P/E) measures a company\'s current share price relative to its per-share earnings. A lower P/E may indicate that the stock is undervalued or that investors expect lower future growth, while a higher P/E suggests high growth expectations.',
    descriptionJa: 'PER（株価収益率）は、株価が1株当たり当期純利益（EPS）の何倍まで買われているかを示す代表的な投資指標です。数値が低いほど割安、高いほど成長期待が高いと判断されます。',
    descriptionZh: '市盈率（P/E）是股票价格与每股收益（EPS）的比率。较低的市盈率通常意味着股票估值偏低，而较高的市盈率反映了市场对公司未来增长的高预期。',
    keyTakeawayKo: 'PER이 낮다고 무조건 매수하기보다, 기업의 이익 성장세가 지속 가능한지 확인해야 합니다.',
    keyTakeawayEn: 'Always verify if earnings growth is sustainable before buying low P/E stocks.',
    relatedCalculatorUrl: '/tools/cagr-calculator',
    relatedCalculatorLabelKo: '복리 수익률(CAGR) 계산기 바로가기',
    relatedTickers: ['005930', 'AAPL', 'NVDA']
  },
  {
    slug: 'pbr',
    termKo: 'PBR (주가순자산비율)',
    termEn: 'PBR (Price to Book Ratio)',
    termJa: 'PBR (株価純資産倍率)',
    termZh: 'PBR (市净率)',
    category: 'valuation',
    formula: 'PBR = 현재 주가 / 주당순자산가치(BPS)',
    formulaDescriptionKo: '기업의 순자산(청산가치) 대비 주가가 몇 배로 평가받고 있는지를 측정하는 안정성 지표입니다.',
    descriptionKo: 'PBR(Price to Book Ratio)은 주가를 1주당 순자산(BPS)으로 나눈 값입니다. PBR이 1배 미만이라는 것은 기업이 지금 당장 사업을 접고 모든 자산을 처분해 주주들에게 배분해도 현재 주가보다 많다는 것을 의미하므로 전통적인 청산가치 기준 저평가 지표로 활용됩니다. 금융주, 지주사, 전통 제조업 분석에 필수적입니다.',
    descriptionEn: 'The Price to Book Ratio (PBR / P/B) compares a firm\'s market capitalization to its book value. A P/B ratio under 1.0 indicates that the stock is trading below its asset liquidation value.',
    descriptionJa: 'PBR（株価純資産倍率）は、株価が1株当たり純資産（BPS）の何倍かを示す指標です。1倍を下回ると解散価値を下回る割安状態とみなされます。',
    descriptionZh: '市净率（P/B）是每股市价与每股净资产的比率。当P/B小于1时，意味着股价低于公司的账面清算价值。',
    keyTakeawayKo: 'PBR 1배 미만 종목은 자산 부실 여부와 주주환원(자사주 소각, 배당) 의지를 확인하는 것이 핵심입니다.',
    keyTakeawayEn: 'Ensure low P/B companies do not suffer from asset impairment or poor governance.',
    relatedCalculatorUrl: '/tools/escape-price-calculator',
    relatedCalculatorLabelKo: '물타기 평단가 탈출 계산기',
    relatedTickers: ['005930', '086790', 'JPM']
  },
  {
    slug: 'roe',
    termKo: 'ROE (자기자본이익률)',
    termEn: 'ROE (Return on Equity)',
    termJa: 'ROE (自己資本利益率)',
    termZh: 'ROE (净资产收益率)',
    category: 'profitability',
    formula: 'ROE = (당기순이익 / 자기자본) × 100 (%)',
    formulaDescriptionKo: '주주가 투자한 순수 자기자본을 활용하여 한 해 동안 몇 %의 순이익을 창출했는지를 나타내는 수익성 지표입니다.',
    descriptionKo: '워런 버핏이 가장 중요하게 여기는 지표 중 하나인 ROE는 주주의 돈(자기자본)으로 얼마나 효율적으로 이익을 창출했는지를 보여줍니다. ROE가 시중 국채 금리나 정기예금 금리보다 현저히 높고 매년 15% 이상을 유지하는 기업은 강력한 경제적 해자(Economic Moat)를 보유하고 있을 가능성이 높습니다.',
    descriptionEn: 'Return on Equity (ROE) measures profitability by revealing how much profit a company generates with the money shareholders have invested.',
    descriptionJa: 'ROE（自己資本利益率）は、自己資本を使ってどれだけの利益を生み出したかを示す指標です。投資価値を測る最重要指標の一つです。',
    descriptionZh: '净资产收益率（ROE）衡量公司利用股东投入的资本赚取利润的能力，是巴菲特最推崇的核心指标之一。',
    keyTakeawayKo: '부채를 과도하게 끌어써서 인위적으로 ROE를 끌어올린 레버리지 착시 현상을 주의해야 합니다.',
    keyTakeawayEn: 'Watch out for artificial ROE spikes caused by excessive debt leverage.',
    relatedCalculatorUrl: '/tools/cagr-calculator',
    relatedCalculatorLabelKo: '연평균 복리 성장률(CAGR) 계산기',
    relatedTickers: ['AAPL', 'MSFT', '005930']
  },
  {
    slug: 'ex-dividend-date',
    termKo: '배당락일 (Ex-Dividend Date)',
    termEn: 'Ex-Dividend Date',
    termJa: '配当落ち日 (Ex-Dividend Date)',
    termZh: '除息日 (Ex-Dividend Date)',
    category: 'dividend',
    formula: '배당락일 = 배당기준일 1영업일 전 (한국 D+2 결제 기준)',
    formulaDescriptionKo: '해당 일자 이후에 주식을 매수하는 투자자에게는 이번 결산기 배당금을 수령할 권리가 주어지지 않는 날입니다.',
    descriptionKo: '배당락일(Ex-Dividend Date)이란 해당 날짜부터 주식을 매수해도 당기 배당금을 받을 권리가 주어지지 않는 날을 말합니다. 주식 시장 결제 제도(D+2 거래일)에 따라, 배당을 받기 위해서는 최소한 배당락일 전 거래일까지 주식을 매수하여 보유하고 있어야 합니다. 배당락 당일에는 배당금만큼 주가가 일시적으로 하락(배당락 현상)하는 경향이 있습니다.',
    descriptionEn: 'The ex-dividend date is the day on which a stock begins trading without the right to receive the next dividend payment. Investors must purchase shares before this date to qualify.',
    descriptionJa: '配当落ち日とは、その日以降に株を買っても直近の配当金を受け取ることができない日のことです。配当を得るには権利付き最終日までに買い付ける必要があります。',
    descriptionZh: '除息日是指从该交易日起买入的股票将不再享有当期派发的股息红利。投资者必须在除息日之前买入才能享受分红。',
    keyTakeawayKo: '배당락일 당일에는 배당수익률에 상응하는 시초가 갭하락이 발생할 수 있으므로 단기 차익 거래 시 주의해야 합니다.',
    keyTakeawayEn: 'Expect a short-term price drop on the ex-dividend date equivalent to the dividend payout.',
    relatedCalculatorUrl: '/tools/dividend-tax-calculator',
    relatedCalculatorLabelKo: '배당소득세 및 실수령액 계산기',
    relatedTickers: ['SCHD', 'O', '005930']
  },
  {
    slug: 'dividend-yield',
    termKo: '시가배당률 (Dividend Yield)',
    termEn: 'Dividend Yield',
    termJa: '配当利回り (Dividend Yield)',
    termZh: '股息率 (Dividend Yield)',
    category: 'dividend',
    formula: '시가배당률 = (1주당 연간 배당금 / 현재 주가) × 100 (%)',
    formulaDescriptionKo: '현재 주가로 주식을 매수했을 때 연간 배당금으로 몇 %의 현금 흐름 수익을 얻을 수 있는지 나타냅니다.',
    descriptionKo: '시가배당률은 투자자가 현재 시점에서 지불하는 주가 대비 연간 얼마의 배당금을 받을 수 있는지를 백분율로 나타낸 값입니다. 정기예금 금리와 비교하여 배당 매력도를 측정하는 핵심 기준이 되며, 주가가 하락하면 배당률이 상승하고 주가가 상승하면 배당률이 낮아지는 특성이 있습니다.',
    descriptionEn: 'Dividend yield indicates how much a company pays out in dividends each year relative to its stock price.',
    descriptionJa: '配当利回りは、現在の株価に対して1年間で受け取れる配当金の割合を示します。銀行預金金利との比較基準になります。',
    descriptionZh: '股息率是公司年度股息与当前股价的比率，是衡量现金分红吸引力的核心指标。',
    keyTakeawayKo: '기업 실적 악화로 주가가 폭락하여 겉보기에만 배당률이 높아 보이는 배당 함정(Dividend Trap)에 주의해야 합니다.',
    keyTakeawayEn: 'Beware of dividend traps where yields spike solely due to steep stock price declines.',
    relatedCalculatorUrl: '/tools/dividend-tax-calculator',
    relatedCalculatorLabelKo: '배당소득세 계산기 바로가기',
    relatedTickers: ['MO', 'O', '033780']
  },
  {
    slug: 'water-down-dca',
    termKo: '물타기 (Dollar-Cost Averaging / 추가 매수)',
    termEn: 'Dollar-Cost Averaging (Watering Down)',
    termJa: 'ナンピン買い (Dollar-Cost Averaging)',
    termZh: '补仓 / 摊薄成本 (Dollar-Cost Averaging)',
    category: 'trading',
    formula: '수정 평균단가 = (기존 보유액 + 추가 매수액) / (기존 주식 수 + 추가 주식 수)',
    formulaDescriptionKo: '주가가 하락했을 때 추가 매수를 단행하여 1주당 평균 매수 단가를 낮추는 투자 전략입니다.',
    descriptionKo: '물타기(Dollar-Cost Averaging / 추가 매수)는 보유 종목의 주가가 하락했을 때 추가 자금을 투입하여 전체 평균 매입 단가를 낮추는 기법입니다. 성공할 경우 주가가 조금만 반등해도 손실 만회 및 본전 탈출이 가능하지만, 기업 펀더멘털이 훼손된 종목에 무계획적으로 물을 탈 경우 비중 과다로 감당할 수 없는 손실에 직면할 수 있습니다.',
    descriptionEn: 'Watering down (Dollar-Cost Averaging on dips) is the strategy of buying more shares as the price drops to lower the average cost basis per share.',
    descriptionJa: 'ナンピン（難平）買いとは、保有株が値下がりしたときに追加購入して平均取得単価を下げる手法です。反発時の回復が早い一方、下落が続くと損失が拡大します。',
    descriptionZh: '补仓是在股票价格下跌后再次买入，以摊低持仓平均成本。若股价反弹可加速回本，但标的恶化时可能导致巨大亏损。',
    keyTakeawayKo: '사전에 분할 매수 횟수와 목표 평단가, 손절 기준을 명확히 세운 후 계획적으로 집행해야 합니다.',
    keyTakeawayEn: 'Always plan your capital allocation limits before averaging down on losing positions.',
    relatedCalculatorUrl: '/tools/escape-price-calculator',
    relatedCalculatorLabelKo: '물타기 평단가 & 본전 탈출 계산기',
    relatedTickers: ['005930', 'TSLA', 'NVDA']
  },
  {
    slug: 'dividend-income-tax',
    termKo: '배당소득세 (Dividend Income Tax)',
    termEn: 'Dividend Income Tax',
    termJa: '配当所得税 (Dividend Income Tax)',
    termZh: '股息红利税 (Dividend Income Tax)',
    category: 'tax',
    formula: '원천징수세액 = 배당금 총액 × 15.4% (지방소득세 1.4% 포함)',
    formulaDescriptionKo: '국내 상장 주식 배당금 수령 시 증권사에서 원천징수되는 15.4%의 소득세율입니다.',
    descriptionKo: '대한민국 세법상 주식 배당금은 배당소득으로 분류되어 지급 시점에 14%의 소득세와 1.4%의 지방소득세가 합산된 15.4%가 원천징수됩니다. 미국 주식의 경우 한미 조세조약에 따라 15%가 현지에서 원천징수되며, 연간 금융소득(이자+배당) 합계액이 2,000만 원을 초과할 경우 타 소득과 합산되는 금융소득종합과세 대상이 됩니다.',
    descriptionEn: 'Dividend income tax is the tax levied on dividend payments received by investors. In Korea, a flat 15.4% is withheld at source up to 20 million KRW annually.',
    descriptionJa: '配当所得税は、受け取った配当金に対して課される税金です。源泉徴収税率や確定申告による総合課税・分離課税の選択が可能です。',
    descriptionZh: '股息红利税是向投资者发放股息红利时按规定扣缴的个人所得税。',
    keyTakeawayKo: '연간 배당금이 2,000만 원에 근접할 경우 ISA 계좌나 연금저축펀드를 활용한 절세 전략이 필수적입니다.',
    keyTakeawayEn: 'Utilize tax-advantaged accounts like ISA or Pension plans when dividends approach tax thresholds.',
    relatedCalculatorUrl: '/tools/dividend-tax-calculator',
    relatedCalculatorLabelKo: '배당소득세 및 실수령액 계산기',
    relatedTickers: ['SCHD', '005930', '086790']
  },
  {
    slug: 'comprehensive-financial-tax',
    termKo: '금융소득종합과세 (Comprehensive Financial Income Tax)',
    termEn: 'Comprehensive Financial Income Taxation',
    termJa: '金融所得総合課税',
    termZh: '综合金融所得税',
    category: 'tax',
    formula: '과세 기준: 연간 이자소득 + 배당소득 > 2,000만 원',
    formulaDescriptionKo: '연간 금융소득 합계가 2,000만 원을 초과하면 초과분이 근로/사업소득과 합산되어 최고 49.5% 누진세율이 적용됩니다.',
    descriptionKo: '금융소득종합과세는 개인별 연간 금융소득(이자소득과 배당소득의 합)이 2,000만 원을 초과하는 경우, 2,000만 원 초과분을 다른 종합소득(근로, 사업, 연금, 기타소득)과 합산하여 기본 누진세율(6%~45%, 지방소득세 포함 최고 49.5%)로 과세하는 제도입니다. 건강보험료 피부양자 자격 박탈 및 지역가입자 건보료 인상으로 이어질 수 있어 철저한 분산 관리가 요구됩니다.',
    descriptionEn: 'Comprehensive taxation applies when annual interest and dividend earnings exceed 20 million KRW, combining with other earned income at progressive rates up to 49.5%.',
    descriptionJa: '金融所得総合課税は、利子・配当所得の合計が一定基準を超えた場合、他の所得と合算して累進税率で課税される制度です。',
    descriptionZh: '综合金融所得税是指个人的利息与股息收入超过年度法定限额（如2000万韩元）时，需合并并入综合所得适用累进税率。',
    keyTakeawayKo: '2,000만 원 초과 시 건보료 인상 위험이 동반되므로 배우자 증여나 비과세 계좌를 통한 사전 절세가 필수입니다.',
    keyTakeawayEn: 'Prepare tax-free accounts and gifting strategies to avoid crossing the 20 million KRW threshold.',
    relatedCalculatorUrl: '/tools/dividend-tax-calculator',
    relatedCalculatorLabelKo: '배당세 및 종합과세 시뮬레이터',
    relatedTickers: ['005930', 'SCHD', 'JEPI']
  },
  {
    slug: 'cagr',
    termKo: 'CAGR (연평균 복리 성장률)',
    termEn: 'CAGR (Compound Annual Growth Rate)',
    termJa: 'CAGR (年平均成長率)',
    termZh: 'CAGR (复合年均增长率)',
    category: 'profitability',
    formula: 'CAGR = (최종 가치 / 초기 가치)^(1 / 기간 년수) - 1',
    formulaDescriptionKo: '여러 해 동안의 투자 성과를 단일한 연간 복리 수익률로 환산하여 장기 성장 추세를 평가하는 표준 공식입니다.',
    descriptionKo: 'CAGR(연평균 복리 성장률)은 투자가 매년 일정 비율로 꾸준히 복리 성장했다고 가정했을 때의 연간 수익률입니다. 단기 시장의 변동성과 왜곡을 제거하고 3년, 5년, 10년 단위의 장기 투자 성과나 기업의 매출 및 순이익 성장세를 객관적으로 비교할 때 가장 신뢰받는 지표입니다.',
    descriptionEn: 'Compound Annual Growth Rate (CAGR) measures the geometric progression ratio that provides a constant rate of return over multiple time periods.',
    descriptionJa: 'CAGR（年平均成長率）は、複数年にわたる成長率を、1年あたりの複利計算で平均化した指標です。',
    descriptionZh: '复合年均增长率（CAGR）是指一项投资在特定时期内的年度复合收益率，能有效平滑短期市场波动。',
    keyTakeawayKo: '단순 산술평균 수익률에 속지 말고, 실제 자산 증식 속도를 측정하려면 반드시 CAGR을 계산해야 합니다.',
    keyTakeawayEn: 'Always use CAGR rather than arithmetic averages to measure realistic wealth compounding.',
    relatedCalculatorUrl: '/tools/cagr-calculator',
    relatedCalculatorLabelKo: 'CAGR 복리 수익률 계산기',
    relatedTickers: ['SPY', 'QQQ', 'AAPL']
  },
  {
    slug: 'eps',
    termKo: 'EPS (주당순이익)',
    termEn: 'EPS (Earnings Per Share)',
    termJa: 'EPS (1株当たり当期純利益)',
    termZh: 'EPS (每股收益)',
    category: 'profitability',
    formula: 'EPS = 당기순이익 / 총 발행 주식 수',
    formulaDescriptionKo: '기업이 한 해 동안 벌어들인 총 순이익을 발행 주식 수로 나눈 것으로, 1주가 창출한 순이익을 뜻합니다.',
    descriptionKo: 'EPS(Earnings Per Share)는 기업의 당기순이익을 유통 주식 수로 나눈 값으로, 1주당 얼마의 순이익을 창출했는지를 나타냅니다. 기업이 자사주를 매입하여 소각하면 순이익이 동일하더라도 주식 수가 줄어들어 EPS가 상승하는 주주친화적 효과가 발생합니다.',
    descriptionEn: 'Earnings Per Share (EPS) represents the portion of a company\'s profit allocated to each outstanding share of common stock.',
    descriptionJa: 'EPS（1株当たり当期純利益）は、純利益を発行済株式数で割った値で、1株あたりの収益力を示します。',
    descriptionZh: '每股收益（EPS）是公司净利润与总发行股数的比率，体现每一股所创造的纯利润。',
    keyTakeawayKo: 'EPS가 매년 우상향하는 기업은 경기 침체기에도 강력한 가격 결정력을 지닌 우량주일 확률이 높습니다.',
    keyTakeawayEn: 'Companies with consistently expanding EPS often possess strong pricing power.',
    relatedCalculatorUrl: '/tools/cagr-calculator',
    relatedCalculatorLabelKo: '기업 이익 복리 성장률 계산기',
    relatedTickers: ['NVDA', 'AAPL', '005930']
  },
  {
    slug: 'bps',
    termKo: 'BPS (주당순자산가치)',
    termEn: 'BPS (Book Value Per Share)',
    termJa: 'BPS (1株当たり純資産)',
    termZh: 'BPS (每股净资产)',
    category: 'valuation',
    formula: 'BPS = 순자산(총자본) / 총 발행 주식 수',
    formulaDescriptionKo: '기업의 총자산에서 총부채를 뺀 순자산을 발행 주식 수로 나눈 1주당 순자산 장부가치입니다.',
    descriptionKo: 'BPS(Book Value Per Share)는 기업의 순자산을 발행 주식 수로 나눈 수치로, 회사가 당장 청산할 경우 주주에게 1주당 분배될 수 있는 자산 가치를 뜻합니다. 주가가 BPS보다 낮다는 것은 PBR 1배 미만 상태를 의미하며, 자산 가치 대비 저평가 여부를 확인하는 기초 자료가 됩니다.',
    descriptionEn: 'Book Value Per Share (BPS) calculates per-share book value by dividing total equity by total outstanding shares.',
    descriptionJa: 'BPS（1株当たり純資産）は、企業の純資産を発行済株式数で割った値で、企業の解散価値に相当します。',
    descriptionZh: '每股净资产（BPS）是公司总净资产与总股本的比值，反映每股代表的账面资产底线。',
    keyTakeawayKo: '자산 중 매출채권이나 재고자산 등 부실화 위험이 있는 자산의 비중이 높지 않은지 확인해야 합니다.',
    keyTakeawayEn: 'Scrutinize tangible vs intangible assets to verify the true quality of BPS.',
    relatedCalculatorUrl: '/tools/escape-price-calculator',
    relatedCalculatorLabelKo: '평단가 탈출 계산기',
    relatedTickers: ['005930', '086790']
  },
  {
    slug: 'short-selling',
    termKo: '공매도 (Short Selling)',
    termEn: 'Short Selling',
    termJa: '空売り (Short Selling)',
    termZh: '做空 / 卖空 (Short Selling)',
    category: 'trading',
    formula: '공매도 수익 = (주식 매도 가격 - 주식 재매수 상환 가격) × 주식 수 - 차입 수수료',
    formulaDescriptionKo: '보유하지 않은 주식을 빌려서 먼저 매도한 후, 주가가 떨어지면 싼값에 되사서 갚아 차익을 얻는 기법입니다.',
    descriptionKo: '공매도는 주가 하락이 예상될 때 주식을 빌려서 매도(선매도)한 후, 실제로 주가가 떨어지면 시장에서 저렴한 가격에 주식을 사서 빌린 주식을 갚음(후매수)으로써 차익을 얻는 투자 기법입니다. 주식 시장의 거품을 제거하고 유동성을 공급하는 순기능이 있는 반면, 주가가 무한정 오를 경우 이론상 손실이 무한대가 될 수 있는 높은 위험을 수반합니다.',
    descriptionEn: 'Short selling involves borrowing shares to sell in hopes that the stock price falls, allowing repurchasing at a lower cost to pocket the spread.',
    descriptionJa: '空売りとは、株価下落を見込んで株式を借りて売り、下落後に買い戻して差額利益を狙う手法です。損失が無限大になるリスクがあります。',
    descriptionZh: '做空是指借入股票先以高价卖出，待股价下跌后再以低价买回还券，以此获取差价收益的交易行为。',
    keyTakeawayKo: '공매도 잔고 비율이 높은 종목은 악재 해소 시 숏스퀴즈(Short Squeeze)로 인한 폭등이 발생할 수 있습니다.',
    keyTakeawayEn: 'High short interest can trigger violent short squeezes when positive catalysts emerge.',
    relatedCalculatorUrl: '/tools/escape-price-calculator',
    relatedCalculatorLabelKo: '손실 복구 탈출가 계산기',
    relatedTickers: ['TSLA', 'GME', '005930']
  },
  {
    slug: 'short-squeeze',
    termKo: '숏스퀴즈 (Short Squeeze)',
    termEn: 'Short Squeeze',
    termJa: 'ショートスクイズ (Short Squeeze)',
    termZh: '空头挤压 / 轧空 (Short Squeeze)',
    category: 'trading',
    formula: '숏스퀴즈 트리거: 급격한 매수세 유입 → 공매도 손실 급증 → 강제 청산 매수세 가세',
    formulaDescriptionKo: '공매도 포지션을 잡은 투자자들이 감당하기 힘든 손실을 막기 위해 패닉 바잉(손절 매수)을 하며 주가가 수직 상승하는 현상입니다.',
    descriptionKo: '숏스퀴즈(Short Squeeze)는 주가 하락을 예상하고 대규모 공매도를 걸었던 세력이 예상치 못한 호재나 매수세로 주가가 오르자, 손실을 제한하기 위해 주식을 황급히 시장가로 사들이는 과정(숏커버링)에서 주가가 비이성적으로 폭등하는 현상입니다. 2021년 게임스탑(GME) 사태가 대표적인 사례입니다.',
    descriptionEn: 'A short squeeze occurs when rapid price increases force short sellers to buy shares to cover losses, driving prices exponentially higher.',
    descriptionJa: 'ショートスクイズとは、空売り勢が急激な株価上昇に耐えきれず買い戻しを余儀なくされ、株価が急騰する現象です。',
    descriptionZh: '轧空是指股价意外暴涨迫使大量空头被迫平仓买入股票止损，从而进一步推升股价暴涨的连锁反应。',
    keyTakeawayKo: '숏스퀴즈로 인한 폭등은 펀더멘털과 무관한 수급 왜곡이므로 고점 추격 매수는 매우 위험합니다.',
    keyTakeawayEn: 'Avoid chasing peaks during short squeezes as prices rapidly mean-revert once covering ends.',
    relatedCalculatorUrl: '/tools/cagr-calculator',
    relatedCalculatorLabelKo: '수익률 변동 시뮬레이터',
    relatedTickers: ['GME', 'AMC', 'TSLA']
  },
  {
    slug: 'stop-loss',
    termKo: '손절매 (Stop-Loss)',
    termEn: 'Stop-Loss',
    termJa: '損切り (Stop-Loss)',
    termZh: '止损 (Stop-Loss)',
    category: 'trading',
    formula: '손절 기준선 = 매수가격 × (1 - 허용 최대 손실률(%))',
    formulaDescriptionKo: '추가적인 큰 손실을 방지하기 위해 정해둔 손실 한도에 도달했을 때 미련 없이 매도하여 리스크를 차단하는 원칙입니다.',
    descriptionKo: '손절매(Stop-Loss, 로스컷)는 투자한 종목의 가격이 매수 가격 대비 일정 수준 이하로 떨어졌을 때, 더 큰 손실을 예방하고 잔여 투자금을 보존하기 위해 손실을 감수하고 매도하는 결단입니다. 투자의 대가들은 하나같이 "수익을 내는 것보다 자본을 지키는 손절 원칙"을 성공적인 투자의 제1원칙으로 꼽습니다.',
    descriptionEn: 'A stop-loss is an order or predetermined rule placed with a broker to sell a security when it reaches a certain price to limit investor loss.',
    descriptionJa: '損切り（ロスカット）とは、保有資産の損失が一定の限度に達した際に売却して損失を確定し、さらなる損失拡大を防ぐ行動です。',
    descriptionZh: '止损是指当股票价格下跌达到预设的最大亏损限度时，果断卖出持仓以避免更大损失的风险控制法则。',
    keyTakeawayKo: '손절매는 감정이 아닌 사전에 정립된 기계적인 원칙과 자동 주문(스톱로스)으로 실행되어야 합니다.',
    keyTakeawayEn: 'Execute stop-losses mechanically rather than emotionally using automated orders.',
    relatedCalculatorUrl: '/tools/escape-price-calculator',
    relatedCalculatorLabelKo: '손실 복구 및 탈출 계산기',
    relatedTickers: ['005930', 'TSLA']
  },
  {
    slug: 'market-cap',
    termKo: '시가총액 (Market Capitalization)',
    termEn: 'Market Capitalization',
    termJa: '時価総額 (Market Capitalization)',
    termZh: '市值 (Market Capitalization)',
    category: 'valuation',
    formula: '시가총액 = 현재 주가 × 총 발행 주식 수',
    formulaDescriptionKo: '주식 시장에서 해당 기업 전체의 가치가 현재 얼마로 평가받고 있는지를 나타내는 시장 가치 총액입니다.',
    descriptionKo: '시가총액(Market Cap)은 현재 주가에 총 발행 주식 수를 곱한 것으로, 기업의 규모와 시장에서의 몸값을 가장 직관적으로 보여주는 지표입니다. 1주당 주가가 비싸다고 해서 큰 기업이 아니며, 시가총액을 확인해야만 기업의 진짜 덩치를 알 수 있습니다. 통상 대형주, 중형주, 소형주를 구분하는 기준이 됩니다.',
    descriptionEn: 'Market capitalization refers to the total dollar market value of a company\'s outstanding shares of stock.',
    descriptionJa: '時価総額は、株価に発行済株式数を掛け合わせたもので、企業の規模や市場価値を表す最重要尺度です。',
    descriptionZh: '市值是指一家上市公司发行在外的所有股票按当前市场价格计算的总价值。',
    keyTakeawayKo: '주가 액면가가 낮아 보인다고 저렴한 주식이 아니며, 반드시 시가총액을 확인해야 합니다.',
    keyTakeawayEn: 'Never judge a stock\'s price cheapness by its nominal share price; look at market cap.',
    relatedCalculatorUrl: '/tools/cagr-calculator',
    relatedCalculatorLabelKo: '기업 가치 성장 시뮬레이터',
    relatedTickers: ['AAPL', 'MSFT', '005930']
  },
  {
    slug: 'ebitda',
    termKo: 'EBITDA (이자·세금·감가상각비 차감 전 영업이익)',
    termEn: 'EBITDA',
    termJa: 'EBITDA (利払い前・税引前・減価償却前利益)',
    termZh: 'EBITDA (息税折旧摊销前利润)',
    category: 'profitability',
    formula: 'EBITDA = 영업이익 + 감가상각비 + 무형자산상각비',
    formulaDescriptionKo: '기업이 순수한 영업 활동을 통해 창출해내는 순수 현금 창출 능력을 나타내는 글로벌 수익성 척도입니다.',
    descriptionKo: 'EBITDA(Earnings Before Interest, Taxes, Depreciation, and Amortization)는 이자비용, 법인세, 유형/무형자산 감가상각비를 차감하기 전의 순수 현금 영업이익입니다. 국가별 상이한 법인세율이나 기업별 자본 조달 구조(부채 비율), 감가상각 회계 처리 방식에 구애받지 않고 기업 본연의 현금 창출력을 비교할 수 있어 글로벌 M&A와 EV/EBITDA 지표에 널리 쓰입니다.',
    descriptionEn: 'EBITDA measures core corporate profitability by looking at cash generated before interest, taxes, depreciation, and amortization.',
    descriptionJa: 'EBITDAは、利払い前・税引き前・減価償却前の利益で、本業で稼ぎ出す現金創出力を純粋に比較するための指標です。',
    descriptionZh: 'EBITDA指息税折旧摊销前利润，消除了不同税率、利息支出及折旧会计政策的影响，直观反映企业核心现金盈利能力。',
    keyTakeawayKo: '대규모 설비투자가 계속 필요한 장치산업에서는 설비 재투자 비용이 누락되므로 맹신을 주의해야 합니다.',
    keyTakeawayEn: 'Be cautious in capital-intensive industries where necessary CapEx is excluded.',
    relatedCalculatorUrl: '/tools/cagr-calculator',
    relatedCalculatorLabelKo: '기업 현금흐름 CAGR 계산기',
    relatedTickers: ['TSMC', '005930', 'AMZN']
  },
  {
    slug: 'ev-ebitda',
    termKo: 'EV/EBITDA (기업가치 대비 상각전영업이익)',
    termEn: 'EV/EBITDA',
    termJa: 'EV/EBITDA倍率',
    termZh: 'EV/EBITDA (企业价值倍数)',
    category: 'valuation',
    formula: 'EV/EBITDA = 기업가치(EV = 시가총액 + 순차입금) / EBITDA',
    formulaDescriptionKo: '기업을 현재 가치로 통째로 인수했을 때, 본업에서 벌어들이는 현금(EBITDA)으로 몇 년 만에 투자금을 회수할 수 있는지를 보여줍니다.',
    descriptionKo: 'EV/EBITDA는 기업의 전체 시장 가치(EV, 순부채를 포함한 인수 총비용)를 영업활동 현금흐름 창출력(EBITDA)으로 나눈 비율입니다. 예를 들어 EV/EBITDA가 5배라면 현재 상태에서 기업을 통째로 매수했을 때 5년 동안 번 돈으로 투자 원금을 전액 회수할 수 있음을 뜻합니다.',
    descriptionEn: 'EV/EBITDA compares a company\'s enterprise value (including debt) to its cash earnings, showing payback years.',
    descriptionJa: 'EV/EBITDAは、買収にかかる全費用を何年分の営業キャッシュフローで回収できるかを示す指標です。',
    descriptionZh: '企业价值倍数（EV/EBITDA）衡量收购整家公司所需的企业价值需要多少年核心经营利润来收回投资成本。',
    keyTakeawayKo: '순부채가 많은 기업도 부채 규모를 반영해 평가하므로 PER보다 더 엄밀한 인수가격 산정이 가능합니다.',
    keyTakeawayEn: 'Accounts for corporate debt structure better than traditional P/E ratios.',
    relatedCalculatorUrl: '/tools/cagr-calculator',
    relatedCalculatorLabelKo: '기업 가치 회수 기간 시뮬레이터',
    relatedTickers: ['005930', 'TSMC', 'AAPL']
  },
  {
    slug: 'operating-margin',
    termKo: '영업이익률 (Operating Profit Margin)',
    termEn: 'Operating Profit Margin',
    termJa: '営業利益率 (Operating Margin)',
    termZh: '营业利润率 (Operating Margin)',
    category: 'profitability',
    formula: '영업이익률 = (영업이익 / 매출액) × 100 (%)',
    formulaDescriptionKo: '매출액 중 본업 비즈니스를 통해 남긴 영업이익의 비율로, 기업의 가격 결정력과 원가 경쟁력을 보여줍니다.',
    descriptionKo: '영업이익률은 기업이 물건이나 서비스를 팔아 남긴 매출액 중에서 본업의 영업이익이 차지하는 비중입니다. 원가 절감 능력이나 브랜드 프리미엄, 독점적 지위를 갖춘 기업일수록 영업이익률이 20%~40% 이상으로 높게 나타나며, 외부 경제 위기에도 안정적인 생존력을 입증합니다.',
    descriptionEn: 'Operating profit margin measures how much profit a company makes upon a dollar of sales after paying for variable costs of production.',
    descriptionJa: '営業利益率は、売上高に対する営業利益の割合で、本業における価格決定力とコスト競争力を示します。',
    descriptionZh: '营业利润率是营业利润与销售收入的比率，体现企业主营业务的定价权和成本控制能力。',
    keyTakeawayKo: '영업이익률이 꾸준히 20%를 넘는 기업은 동종 업계 경쟁자들을 압도하는 강력한 해자를 가지고 있습니다.',
    keyTakeawayEn: 'Margins consistently exceeding 20% indicate a robust competitive moat.',
    relatedCalculatorUrl: '/tools/cagr-calculator',
    relatedCalculatorLabelKo: '수익성 복리 시뮬레이터',
    relatedTickers: ['NVDA', 'MSFT', 'AAPL']
  },
  {
    slug: 'net-profit-margin',
    termKo: '순이익률 (Net Profit Margin)',
    termEn: 'Net Profit Margin',
    termJa: '純利益率 (Net Margin)',
    termZh: '净利润率 (Net Margin)',
    category: 'profitability',
    formula: '순이익률 = (당기순이익 / 매출액) × 100 (%)',
    formulaDescriptionKo: '매출액에서 모든 비용(원가, 판관비, 이자, 세금, 일회성 손익)을 제하고 최종 주주 몫으로 남은 순이익의 비율입니다.',
    descriptionKo: '순이익률은 기업이 거둔 총매출액 중 모든 비용과 세금을 제한 뒤 최종적으로 주주 지분으로 남는 당기순이익의 비율입니다. 영업이익률이 높아도 과도한 부채 이자나 일회성 소송 비용이 발생하면 순이익률이 급감할 수 있으므로 두 지표를 교차 검증해야 합니다.',
    descriptionEn: 'Net profit margin illustrates the percentage of revenue remaining after all operating expenses, taxes, and interest are settled.',
    descriptionJa: '純利益率は、売上高に対する当期純利益の割合で、最終的に会社・株主に残る利益の割合を表します。',
    descriptionZh: '净利润率是最终归属于股东的净利润占营业收入的百分比，反映企业最终的盈利转化底线。',
    keyTakeawayKo: '일회성 자산 매각으로 일시적으로 튄 순이익률인지 지속 가능한 순이익인지 손익계산서를 확인해야 합니다.',
    keyTakeawayEn: 'Differentiate one-off asset sale windfalls from core recurring profitability.',
    relatedCalculatorUrl: '/tools/cagr-calculator',
    relatedCalculatorLabelKo: '순이익 성장률 계산기',
    relatedTickers: ['AAPL', 'GOOGL', '005930']
  },
  {
    slug: 'dividend-payout-ratio',
    termKo: '배당성향 (Dividend Payout Ratio)',
    termEn: 'Dividend Payout Ratio',
    termJa: '配当性向 (Payout Ratio)',
    termZh: '股利支付率 (Payout Ratio)',
    category: 'dividend',
    formula: '배당성향 = (총 배당금 지급액 / 당기순이익) × 100 (%)',
    formulaDescriptionKo: '기업이 한 해 동안 벌어들인 순이익 중 얼마를 주주들에게 현금 배당으로 환원했는지를 나타냅니다.',
    descriptionKo: '배당성향은 순이익 중 배당금으로 지급된 비율입니다. 배당성향이 30%~50% 수준인 기업은 안정적인 배당과 미래 재투자의 균형을 갖춘 것으로 평가받습니다. 반면 배당성향이 100%를 초과하는 기업은 번 돈보다 더 많은 배당을 지급하고 있어 배당 삭감(Dividend Cut) 위험이 큽니다.',
    descriptionEn: 'The dividend payout ratio shows the percentage of net income paid out as dividends to shareholders.',
    descriptionJa: '配当性向は、純利益のうち配当金として株主に還元した割合を示します。',
    descriptionZh: '股利支付率表示公司将当年净利润中的多少比例作为现金红利分配给股东。',
    keyTakeawayKo: '배당성향이 80%를 넘는 고배당주는 경기 침체 시 배당 삭감 위험이 매우 높습니다.',
    keyTakeawayEn: 'Payout ratios over 80% face heightened risks of dividend cuts during recessions.',
    relatedCalculatorUrl: '/tools/dividend-tax-calculator',
    relatedCalculatorLabelKo: '배당금 지속 가능성 & 세금 계산기',
    relatedTickers: ['KO', 'JNJ', '033780']
  },
  {
    slug: 'dividend-aristocrat',
    termKo: '배당귀족주 (Dividend Aristocrats)',
    termEn: 'Dividend Aristocrats',
    termJa: '配当貴族 (Dividend Aristocrats)',
    termZh: '股息贵族 (Dividend Aristocrats)',
    category: 'dividend',
    formula: '자격 요건: S&P 500 소속 + 25년 이상 연속 배당금 인상 기업',
    formulaDescriptionKo: '25년 이상 단 한 해도 거르지 않고 주당 배당금을 지속적으로 인상해온 초우량 검증 기업들을 지칭합니다.',
    descriptionKo: '배당귀족주는 미국 S&P 500 지수 편입 기업 중 최소 25년 연속으로 매년 주당 배당금을 늘려온 기업들을 의미합니다. 2000년 닷컴 버블, 2008년 글로벌 금융위기, 2020년 팬데믹 등 극심한 경기 침체기에도 이익을 창출하고 배당을 늘려왔다는 점에서 장기 복리 투자자들에게 최고의 안정성을 제공합니다.',
    descriptionEn: 'Dividend Aristocrats are S&P 500 companies that have consistently increased their dividend payouts for 25 consecutive years or more.',
    descriptionJa: '配当貴族とは、25年以上連続して増配を続けている優良な米国株を指します。危機への耐性と安定した還元が特徴です。',
    descriptionZh: '股息贵族是指标准普尔500指数成分股中连续25年以上每年都增加分红的超优质蓝筹股。',
    keyTakeawayKo: '배당 인상률이 물가상승률(인플레이션)을 웃도는 배당귀족주는 최고의 실물자산 방어 수단입니다.',
    keyTakeawayEn: 'Aristocrats whose dividend growth outpaces inflation offer superior purchasing power protection.',
    relatedCalculatorUrl: '/tools/dividend-tax-calculator',
    relatedCalculatorLabelKo: '배당 성장 복리 실수령액 계산기',
    relatedTickers: ['JNJ', 'PG', 'KO']
  },
  {
    slug: 'dividend-king',
    termKo: '배당킹 (Dividend Kings)',
    termEn: 'Dividend Kings',
    termJa: '配当王 (Dividend Kings)',
    termZh: '股息国王 (Dividend Kings)',
    category: 'dividend',
    formula: '자격 요건: 50년 이상 연속 배당금 인상 기업',
    formulaDescriptionKo: '반세기(50년)가 넘는 세월 동안 매년 연속으로 배당금을 늘려온 최상위 배당 챔피언 기업들입니다.',
    descriptionKo: '배당킹(Dividend Kings)은 미국 주식 시장에서 무려 50년 이상 연속으로 배당금을 증액해온 전설적인 기업들입니다. 배당귀족주(25년)의 기준을 두 배나 뛰어넘는 기록으로, 3M, 프록터앤갬블(P&G), 코카콜라 등이 대표적입니다. 어떠한 지정학적 위기나 산업 패러다임 변화 속에서도 살아남은 강력한 해자를 상징합니다.',
    descriptionEn: 'Dividend Kings are exceptional corporations that have increased dividend payments for 50 or more consecutive years.',
    descriptionJa: '配当王とは、半世紀（50年）以上にわたり毎年連続増配を継続している極めて稀有な優良企業です。',
    descriptionZh: '股息国王是连续50年以上每年不间断提高每股现金分红的传奇企业。',
    keyTakeawayKo: '반세기 동안 검증된 현금 창출력 덕분에 은퇴 준비용 연금형 포트폴리오의 든든한 초석이 됩니다.',
    keyTakeawayEn: 'Forms the rock-solid bedrock for retirement cash-flow portfolios.',
    relatedCalculatorUrl: '/tools/dividend-tax-calculator',
    relatedCalculatorLabelKo: '은퇴 배당 연금 계산기',
    relatedTickers: ['KO', 'PG', 'MMM']
  },
  {
    slug: 'debt-to-equity-ratio',
    termKo: '부채비율 (Debt to Equity Ratio)',
    termEn: 'Debt to Equity Ratio',
    termJa: '負債比率 (Debt to Equity)',
    termZh: '资产负债率 / 产权比率',
    category: 'valuation',
    formula: '부채비율 = (총부채 / 자기자본) × 100 (%)',
    formulaDescriptionKo: '기업이 가진 밑천(자기자본) 대비 빚(타인자본)이 몇 배인지를 측정하는 대표적인 재무 건전성 지표입니다.',
    descriptionKo: '부채비율은 기업의 타인자본(부채) 의존도를 나타내는 비율입니다. 일반적으로 100% 이하를 매우 우량한 상태로 보며, 200%를 초과하면 고금리 경기 침체기에 이자 부담으로 인한 재무 위기 발생 가능성이 높아집니다. 금융업종 등 산업 특성에 따라 적정 기준이 상이합니다.',
    descriptionEn: 'The debt-to-equity ratio calculates the proportion of company financing that comes from debt relative to equity.',
    descriptionJa: '負債比率は、自己資本に対する他人資本（負債）の割合で、企業の財務的健全性や倒産リスクを評価します。',
    descriptionZh: '产权比率衡量企业总负债与所有者权益的比值，反映财务杠杆水平与长期偿债风险。',
    keyTakeawayKo: '금리 인상기에는 부채비율이 높은 기업의 순이익이 급감하므로 재무 건전성을 필히 확인해야 합니다.',
    keyTakeawayEn: 'Scrutinize high debt-to-equity firms during monetary tightening as interest costs surge.',
    relatedCalculatorUrl: '/tools/loan-interest-calculator',
    relatedCalculatorLabelKo: '대출 이자 및 원리금 상환 계산기',
    relatedTickers: ['005930', '086790']
  },
  {
    slug: 'current-ratio',
    termKo: '유동비율 (Current Ratio)',
    termEn: 'Current Ratio',
    termJa: '流動比率 (Current Ratio)',
    termZh: '流动比率 (Current Ratio)',
    category: 'valuation',
    formula: '유동비율 = (유동자산 / 유동부채) × 100 (%)',
    formulaDescriptionKo: '1년 내에 현금화할 수 있는 자산이 1년 내에 갚아야 할 단기 부채의 몇 배인지를 나타내는 단기 지급능력 지표입니다.',
    descriptionKo: '유동비율은 기업이 1년 이내에 현금화할 수 있는 유동자산을 1년 이내에 만기가 도래하는 유동부채로 나눈 값입니다. 통상 200% 이상을 가장 이상적이고 안전한 수준으로 평가하며, 100% 미만으로 떨어지면 단기 유동성 위기(흑자도산 위험)를 겪을 수 있습니다.',
    descriptionEn: 'The current ratio measures a company\'s ability to pay short-term obligations due within one year using liquid assets.',
    descriptionJa: '流動比率は、1年以内に返済すべき流動負債に対する1年以内に換金可能な流動資産の比率で、短期的な支払い能力を示します。',
    descriptionZh: '流动比率是流动资产与流动负债的比率，衡量企业偿还短期债务的能力。',
    keyTakeawayKo: '유동비율이 높아도 재고자산이 악성 재고로 묶여 있다면 실제 현금 동원력은 떨어질 수 있습니다.',
    keyTakeawayEn: 'Deduct illiquid inventory to calculate the Quick Ratio for a more realistic safety check.',
    relatedCalculatorUrl: '/tools/loan-interest-calculator',
    relatedCalculatorLabelKo: '단기 대출 상환 부담 계산기',
    relatedTickers: ['005930', 'AAPL']
  },
  {
    slug: 'operating-cash-flow',
    termKo: '영업활동현금흐름 (Operating Cash Flow / OCF)',
    termEn: 'Operating Cash Flow (OCF)',
    termJa: '営業キャッシュフロー (OCF)',
    termZh: '经营活动现金流 (OCF)',
    category: 'profitability',
    formula: '영업현금흐름 = 당기순이익 + 비현금비용(감가상각 등) ± 운전자본 변동',
    formulaDescriptionKo: '회계상 장부상 이익이 아닌, 본업 비즈니스를 통해 회사 통장에 실제로 들어온 순수한 현금 유입액입니다.',
    descriptionKo: '영업활동현금흐름(OCF)은 기업의 본원적 비즈니스 활동을 통해 실제로 창출된 현금의 총량입니다. 장부상 당기순이익은 흑자라도 거래처 미수금 증가나 재고 누적으로 실제 현금이 들어오지 않으면 흑자도산에 빠질 수 있습니다. 따라서 우량 기업은 당기순이익보다 영업활동현금흐름이 항상 더 크고 안정적인 양수(+)를 기록합니다.',
    descriptionEn: 'Operating cash flow (OCF) indicates the cash generated by core business operations, reflecting true liquidity.',
    descriptionJa: '営業活動によるキャッシュフローは、本業の営業活動から実際に獲得した現金の流れを示し、会計上の利益よりも確実な指標です。',
    descriptionZh: '经营活动产生的现金流量净额反映企业核心业务实际收到的真金白银，是检验真实盈利质量的试金石。',
    keyTakeawayKo: '당기순이익은 큰데 영업현금흐름이 마이너스(-)라면 분식회계나 매출채권 회수 불능 위험을 의심해야 합니다.',
    keyTakeawayEn: 'Divergence between growing net income and negative OCF often signals accounting red flags.',
    relatedCalculatorUrl: '/tools/cagr-calculator',
    relatedCalculatorLabelKo: '현금 창출 복리 성장률 계산기',
    relatedTickers: ['AAPL', 'MSFT', 'AMZN']
  },
  {
    slug: 'free-cash-flow',
    termKo: '잉여현금흐름 (Free Cash Flow / FCF)',
    termEn: 'Free Cash Flow (FCF)',
    termJa: 'フリーキャッシュフロー (FCF)',
    termZh: '自由现金流 (FCF)',
    category: 'profitability',
    formula: 'FCF = 영업활동현금흐름 - 설비투자비(CapEx)',
    formulaDescriptionKo: '영업으로 번 실제 현금 중 사업 유지를 위한 필수 설비투자를 모두 마친 뒤 온전히 주주 몫으로 남은 자유 현금입니다.',
    descriptionKo: '잉여현금흐름(FCF)은 기업이 영업활동으로 벌어들인 현금에서 사업 경쟁력 유지를 위해 필수적인 자본적 지출(CapEx, 공장 증설·설비 유지비 등)을 차감하고 남은 순수 잉여 현금입니다. 이 돈으로 배당금을 지급하고, 자사주를 매입하며, 신규 사업을 인수할 수 있으므로 기업의 실제 주주환원 여력을 가늠하는 최상위 척도입니다.',
    descriptionEn: 'Free Cash Flow represents the cash a company generates after accounting for cash outflows to support operations and maintain its capital assets.',
    descriptionJa: 'フリーキャッシュフローは、事業で得た現金から設備投資額を差し引いた、会社が自由に使用できる余剰資金です。',
    descriptionZh: '自由现金流（FCF）是企业经营现金流扣除维持正常运营及资本支出（CapEx）后剩余的纯现金，决定了分红与回购的能力。',
    keyTakeawayKo: 'FCF가 풍부한 기업만이 경기 침체기에도 배당을 삭감하지 않고 대규모 자사주 소각을 단행할 수 있습니다.',
    keyTakeawayEn: 'Strong FCF is the true engine powering sustainable dividend growth and aggressive buybacks.',
    relatedCalculatorUrl: '/tools/dividend-tax-calculator',
    relatedCalculatorLabelKo: '배당 가능 재원 & 세금 계산기',
    relatedTickers: ['AAPL', 'GOOGL', 'NVDA']
  },
  {
    slug: 'dca-dollar-cost-averaging',
    termKo: '적립식 분할 투자 (DCA / 정액매수적립식)',
    termEn: 'Dollar-Cost Averaging (DCA)',
    termJa: 'ドルコスト平均法 (DCA)',
    termZh: '定期定额定投 (DCA)',
    category: 'trading',
    formula: 'DCA 매입량 = 정기 투자 고정 금액 / 해당 시점 주가',
    formulaDescriptionKo: '주가 등락과 무관하게 일정한 주기로 일정한 금액을 꾸준히 매수하여 매입 단가를 자연스럽게 평준화하는 장기 투자법입니다.',
    descriptionKo: 'DCA(정액매수적립식)는 주가가 높을 때는 적은 수량을 매수하고 주가가 낮을 때는 많은 수량을 자동으로 매수하게 되어 장기적으로 평균 매입 단가를 낮추는 투자 전략입니다. 시장의 단기 고점과 저점을 맞추려는 심리적 스트레스를 제거하고 복리 효과를 극대화할 수 있어 직장인과 장기 투자자에게 가장 권장되는 방식입니다.',
    descriptionEn: 'Dollar-cost averaging (DCA) is an investment strategy where fixed amounts are invested at regular intervals regardless of share price.',
    descriptionJa: 'ドルコスト平均法は、価格変動に関わらず定期的に一定金額を投資し続けることで、平均購入単価を平準化する投資手法です。',
    descriptionZh: '定期定额定投（DCA）是指不择时机在固定周期投入固定金额购买资产，通过长期均摊拉低平均持仓成本。',
    keyTakeawayKo: '우상향하는 지수 ETF(S&P 500, 나스닥 100)와 결합했을 때 가장 강력한 자산 증식 효과를 발휘합니다.',
    keyTakeawayEn: 'Combines most powerfully with broad-market index ETFs with long-term upward trajectories.',
    relatedCalculatorUrl: '/tools/cagr-calculator',
    relatedCalculatorLabelKo: '적립식 복리 적금 & 투자 계산기',
    relatedTickers: ['SPY', 'VOO', 'QQQ']
  },
  {
    slug: 'market-order',
    termKo: '시장가 주문 (Market Order)',
    termEn: 'Market Order',
    termJa: '成行注文 (Market Order)',
    termZh: '市价单 (Market Order)',
    category: 'trading',
    formula: '체결 우선순위: 가격 불문 즉시 최우선 체결',
    formulaDescriptionKo: '가격을 지정하지 않고 현재 호가창에 나와 있는 가장 유리한 가격으로 즉각 체결시키는 주문 방식입니다.',
    descriptionKo: '시장가 주문은 가격을 따지지 않고 수량만 지정하여 주문을 넣는 순간 즉시 체결을 보장받는 주문 형태입니다. 빠른 포지션 진입이나 긴급한 손절매가 필요할 때 유용하지만, 거래량이 적은 종목의 경우 호가 공백으로 인해 예상보다 훨씬 불리한 가격에 체결(슬리피지)될 수 있는 위험이 있습니다.',
    descriptionEn: 'A market order is a request to buy or sell a security immediately at the best available current price.',
    descriptionJa: '成行注文は、値段を指定せずに現在の市場価格で即座に取引を成立させる注文方法です。スリッページに注意が必要です。',
    descriptionZh: '市价单是指不设定具体的交易价格，按照当前市场上最优可用报价立即撮合成交的委托指令。',
    keyTakeawayKo: '호가창이 얇은 중소형주나 장 시작 직후 변동성이 극심할 때는 슬리피지 방지를 위해 지정가 주문을 권장합니다.',
    keyTakeawayEn: 'Prefer limit orders on illiquid tickers to prevent aggressive slippage.',
    relatedCalculatorUrl: '/tools/escape-price-calculator',
    relatedCalculatorLabelKo: '탈출 단가 시뮬레이터',
    relatedTickers: ['005930', 'TSLA']
  },
  {
    slug: 'limit-order',
    termKo: '지정가 주문 (Limit Order)',
    termEn: 'Limit Order',
    termJa: '指値注文 (Limit Order)',
    termZh: '限价单 (Limit Order)',
    category: 'trading',
    formula: '체결 조건: 매수 시 지정 가격 이하, 매도 시 지정 가격 이상에서만 체결',
    formulaDescriptionKo: '투자자가 원하는 매수/매도 상한선·하한선 가격을 지정하여 불리한 가격에 체결되는 것을 방지하는 주문입니다.',
    descriptionKo: '지정가 주문은 투자자가 지정한 가격 또는 그보다 유리한 가격에서만 거래가 체결되도록 하는 방식입니다. 매수 시에는 지정가 이하, 매도 시에는 지정가 이상에서만 체결되므로 슬리피지를 방지할 수 있습니다. 단, 주가가 지정 가격에 도달하지 않으면 체결되지 않고 주문이 취소될 수 있습니다.',
    descriptionEn: 'A limit order is an order to buy or sell a stock at a specific target price or better.',
    descriptionJa: '指値注文は、希望する売買価格を指定して発注し、その価格かそれ以上の有利な条件で約定させる注文方法です。',
    descriptionZh: '限价单是指由交易者限定买入的最高价或卖出的最低价，只有达到该价格或更优条件时才会撮合成交。',
    keyTakeawayKo: '원하는 유리한 가격을 보장받는 대신 거래 미체결 위험이 존재한다는 트레이드오프가 있습니다.',
    keyTakeawayEn: 'Guarantees execution price quality at the expense of potential non-execution risk.',
    relatedCalculatorUrl: '/tools/escape-price-calculator',
    relatedCalculatorLabelKo: '목표 탈출 지정가 계산기',
    relatedTickers: ['005930', 'AAPL']
  },
  {
    slug: 'beta-coefficient',
    termKo: '베타 계수 (Beta)',
    termEn: 'Beta Coefficient',
    termJa: 'ベータ値 (Beta)',
    termZh: '贝塔系数 (Beta)',
    category: 'trading',
    formula: 'Beta = Covariance(종목 수익률, 시장 수익률) / Variance(시장 수익률)',
    formulaDescriptionKo: '시장 지수(KOSPI, S&P 500)가 1% 변동할 때 해당 종목이 얼마나 민감하게 반응하는지를 측정하는 변동성 계수입니다.',
    descriptionKo: '베타(Beta)는 시장 전체의 변동 대비 특정 주식의 민감도를 측정하는 지표입니다. 시장(코스피 또는 S&P 500)의 베타는 1.0입니다. 베타가 1.5인 종목은 시장이 10% 상승할 때 15% 상승하지만 시장이 10% 폭락할 때 15% 폭락합니다. 반대로 필수소비재나 유틸리티 같은 방어주는 베타가 0.5 수준으로 시장 변동에 둔감합니다.',
    descriptionEn: 'Beta measures a stock\'s systemic volatility and sensitivity in relation to the overall market benchmark.',
    descriptionJa: 'ベータ値は、市場全体の動きに対する個別の株式の感응度（ボラティリティ）を示す係数です。',
    descriptionZh: '贝塔系数衡量个股或投资组合相对于整体市场基准波动的敏感度和系统性风险。',
    keyTakeawayKo: '상승장에서는 고베타 성장주가 유리하고, 하락장이나 침체기에는 저베타 방어주가 자산을 지켜줍니다.',
    keyTakeawayEn: 'Deploy high-beta stocks in bull runs and low-beta defensives during market turmoil.',
    relatedCalculatorUrl: '/tools/cagr-calculator',
    relatedCalculatorLabelKo: '포트폴리오 변동성 시뮬레이터',
    relatedTickers: ['TSLA', 'NVDA', 'KO']
  },
  {
    slug: 'inflation',
    termKo: '인플레이션 (물가상승률)',
    termEn: 'Inflation Rate',
    termJa: 'インフレーション (物価上昇率)',
    termZh: '通货膨胀率 (Inflation)',
    category: 'macro',
    formula: '실질 수익률 = 명목 수익률 - 인플레이션율',
    formulaDescriptionKo: '화폐 가치가 하락하여 전반적인 물가 수준이 지속적으로 상승하는 현상으로, 현금 자산의 실질 구매력을 갉아먹습니다.',
    descriptionKo: '인플레이션(Inflation)은 통화량 증가 등으로 화폐 가치가 하락하여 상품과 서비스의 전반적인 가격 수준이 지속적으로 상승하는 현상입니다. 연 3%의 인플레이션이 발생하면 1억 원의 실질 구매력은 10년 뒤 약 7,400만 원으로 줄어듭니다. 따라서 물가상승률을 초과하는 실질 자산(우량 주식, 부동산, 원자재)에 투자해야 자산의 실질 가치를 방어할 수 있습니다.',
    descriptionEn: 'Inflation measures the rate of rising prices across goods and services, diminishing purchasing power over time.',
    descriptionJa: 'インフレは、通貨価値の下落に伴いモノやサービスの物価が継続的に上昇し、購買力を低下させる現象です。',
    descriptionZh: '通货膨胀是指流通中的货币贬值导致的商品和劳务价格总体水平持续上涨，削弱实际购买力。',
    keyTakeawayKo: '단순 은행 예금은 인플레이션 세금에 의해 실질 자산이 매년 축소되므로 복리 자산 배분이 필수입니다.',
    keyTakeawayEn: 'Keeping idle cash guarantees purchasing power erosion against compounding inflation.',
    relatedCalculatorUrl: '/tools/cagr-calculator',
    relatedCalculatorLabelKo: '실질 복리 자산 가치 계산기',
    relatedTickers: ['SPY', 'GLD']
  },
  {
    slug: 'fed-funds-rate',
    termKo: '미국 기준금리 (Fed Funds Rate)',
    termEn: 'Federal Funds Rate',
    termJa: '米連邦準備制度基準金利',
    termZh: '美联储基准利率',
    category: 'macro',
    formula: '영향: 기준금리 인상 → 할인율 상승 → 고PER 성장주 밸류에이션 하락',
    formulaDescriptionKo: '미국 중앙은행(연준, Fed)이 설정하는 초단기 대출 목표 금리로, 전 세계 모든 자산 가격의 할인율 기준이 됩니다.',
    descriptionKo: '미국 기준금리는 미국 연방준비제도(Fed)가 시중 통화량을 조절하기 위해 설정하는 정책 금리입니다. 글로벌 기축통화인 달러의 기준금리는 전 세계 자산 가격의 할인율 역할을 합니다. 금리가 인상되면 미래 현금흐름의 현재 가치가 할인되어 성장주 주가가 압박을 받고, 금리가 인하되면 유동성이 공급되어 주식과 자산 시장이 활성화됩니다.',
    descriptionEn: 'The Federal Funds Rate is the target interest rate set by the Fed at which commercial banks borrow and lend overnight reserves.',
    descriptionJa: '米フェデラルファンド金利は、世界中の金融資産の割引率の基準となる最重要のマクロ経済指標です。',
    descriptionZh: '美联储基准利率是全球金融市场的资产定价锚，直接决定跨国流动性与成长股估值贴现率。',
    keyTakeawayKo: '금리 전환기(피벗)에는 채권 듀레이션 및 고배당 가치주의 상대적 매력도가 크게 변화합니다.',
    keyTakeawayEn: 'Rate pivot points dramatically alter the relative risk-reward of growth vs dividend assets.',
    relatedCalculatorUrl: '/tools/loan-interest-calculator',
    relatedCalculatorLabelKo: '금리 변동 대출이자 시뮬레이터',
    relatedTickers: ['TLT', 'SPY']
  },
  {
    slug: 'isa-account',
    termKo: 'ISA 개인종합자산관리계좌',
    termEn: 'ISA (Individual Savings Account)',
    termJa: 'ISA (韓国版少額投資非課税口座)',
    termZh: 'ISA 个人综合储蓄账户',
    category: 'tax',
    formula: '비과세 한도: 일반형 200만 원 (서민형 400만 원), 초과분 9.9% 분리과세',
    formulaDescriptionKo: '한 계좌에서 예금, 펀드, ETF, 국내 주식을 굴리며 이자·배당소득을 손익통산하여 절세 혜택을 받는 만능 비과세 통장입니다.',
    descriptionKo: 'ISA(개인종합자산관리계좌)는 정부가 국민의 자산 형성을 지원하기 위해 만든 절세 계좌입니다. 계좌 내에서 발생한 이익과 손실을 상계(손익통산)한 후 순이익에 대해 200만~400만 원까지 전액 비과세하며, 비과세 한도 초과분에 대해서도 15.4%가 아닌 9.9% 저율 분리과세가 적용되어 금융소득종합과세 합산을 회피할 수 있는 최적의 계좌입니다.',
    descriptionEn: 'Korea\'s ISA offers tax exemption up to 2-4 million KRW on investment profits and a reduced 9.9% separate withholding rate beyond.',
    descriptionJa: 'ISAは、株式・ETF・預金の損益を通算し、一定額の非課税枠と低税率分離課税（9.9%）が適用される韓国の優遇税制口座です。',
    descriptionZh: 'ISA账户是韩国推出的综合节税账户，支持盈亏相抵，提供法定非课税额度及9.9%低税率单独征税。',
    keyTakeawayKo: '배당 ETF나 국내 주식 고배당주 투자 시 일반 계좌 대신 ISA를 우선 활용하는 것이 세후 수익률을 극대화합니다.',
    keyTakeawayEn: 'Always route domestic high-dividend ETFs through ISA accounts to maximize net returns.',
    relatedCalculatorUrl: '/tools/dividend-tax-calculator',
    relatedCalculatorLabelKo: 'ISA 절세 효과 배당 계산기',
    relatedTickers: ['005930', '086790']
  },
  {
    slug: 'split-buy',
    termKo: '분할 매수 (Pyramiding / Scale-In)',
    termEn: 'Scale-In Purchasing',
    termJa: '分割買い (Scale-In)',
    termZh: '分批建仓 (Scale-In)',
    category: 'trading',
    formula: '자금 배분: 1차 30% → 2차 30% → 3차 40% (단계별 지지선 분할)',
    formulaDescriptionKo: '보유 자금을 한 번에 투입하지 않고 목표 지지선이나 시간 간격을 두고 여러 차례로 나누어 진입하는 리스크 관리법입니다.',
    descriptionKo: '분할 매수는 시장의 불확실성을 인정하고 리스크를 최소화하기 위해 자금을 3회~5회 이상으로 나누어 매수하는 전략입니다. 주가가 예상과 달리 급락하더라도 다음 매수 기회에서 더 싼 가격에 평균 단가를 낮출 수 있는 현금 버퍼를 제공하며, 심리적 공포를 극복하고 원칙 투자를 가능하게 만듭니다.',
    descriptionEn: 'Scaling in involves dividing total capital into multiple tranches to buy shares gradually across key price supports.',
    descriptionJa: '分割買いとは、資金を一度に投入せず複数回に分けて買い付けることで、高値掴みのリスクを分散する規律ある手法です。',
    descriptionZh: '分批建仓是将总资金划分为多个批次逐步买入，避免一次性重仓在高点的避险交易策略。',
    keyTakeawayKo: '몰빵(올인)의 유혹을 이겨내고 현금 비중을 남겨두는 것 자체가 가장 강력한 헷지 수단입니다.',
    keyTakeawayEn: 'Retaining reserve liquidity is inherently the most effective structural hedge.',
    relatedCalculatorUrl: '/tools/escape-price-calculator',
    relatedCalculatorLabelKo: '분할 매수 평단가 계산기',
    relatedTickers: ['005930', 'NVDA']
  },
  {
    slug: 'split-sell',
    termKo: '분할 매도 (Scale-Out / 익절 분할)',
    termEn: 'Scale-Out Selling',
    termJa: '分割売り (Scale-Out)',
    termZh: '分批止盈 (Scale-Out)',
    category: 'trading',
    formula: '익절 분할: +10% 도달 시 30% 매도 → +20% 도달 시 30% 매도 → 잔여 40% 추세 추종',
    formulaDescriptionKo: '수익이 발생했을 때 전량을 한 번에 매도하지 않고 구간별로 이익을 실현하여 수익을 보존하면서 추가 상승을 향유하는 기법입니다.',
    descriptionKo: '분할 매도는 목표 수익률에 도달했을 때 보유 물량의 일부(예: 30%~50%)를 매도하여 원금과 확정 수익을 챙기고, 나머지 물량은 추세선이 꺾일 때까지 길게 끌고 가며 수익을 극대화하는 출구 전략입니다. 고점에서 전량을 매도하려는 욕심을 버리고 안전하게 수익을 잠글 수 있습니다.',
    descriptionEn: 'Scaling out means selling portions of a winning position incrementally to lock in profit while letting runner shares trend.',
    descriptionJa: '分割売りとは、利益が出ているポジションを一括ではなく段階的に利確し、利益を確保しつつさらなる上昇も狙う手法です。',
    descriptionZh: '分批止盈是指在达到目标收益时逐步卖出部分持仓锁定利润，剩余仓位继续跟随主升浪趋势。',
    keyTakeawayKo: '원금을 회수한 상태에서 남은 물량으로 편안하게 복리 상승을 누리는 심리적 안정이 핵심입니다.',
    keyTakeawayEn: 'Taking off initial principal allows psychological tranquility to ride remainder runners.',
    relatedCalculatorUrl: '/tools/cagr-calculator',
    relatedCalculatorLabelKo: '복리 수익 보존 계산기',
    relatedTickers: ['NVDA', 'AAPL']
  },
  {
    slug: 'golden-cross',
    termKo: '골든크로스 (Golden Cross)',
    termEn: 'Golden Cross',
    termJa: 'ゴールデンクロス (Golden Cross)',
    termZh: '金叉 / 黄金交叉 (Golden Cross)',
    category: 'trading',
    formula: '신호: 단기 이동평균선(20일/50일)이 장기 이동평균선(60일/200일)을 아래에서 위로 상향 돌파',
    formulaDescriptionKo: '최근의 단기 매수세가 장기 평균을 뚫고 올라서며 본격적인 중장기 상승 추세 전환을 알리는 기술적 분석 신호입니다.',
    descriptionKo: '골든크로스는 차트 분석에서 단기 이동평균선이 장기 이동평균선을 상향 돌파하는 현상으로, 강력한 강세장 진입 신호로 해석됩니다. 특히 50일선이 200일선을 뚫는 대형 골든크로스는 기관 투자자들의 알고리즘 매수세를 촉발하여 중장기적인 랠리를 이끄는 모멘텀이 됩니다.',
    descriptionEn: 'A golden cross occurs when a short-term moving average crosses above a major long-term moving average, signaling bullish trends.',
    descriptionJa: 'ゴールデンクロスは、短期移動平均線が長期移動平均線を下から上に突き抜けるチャートパターンで、上昇トレンド入りのシグナルです。',
    descriptionZh: '黄金交叉是指较短周期的移动平均线向上穿越较长周期移动平均线，预示着强劲的牛市转折。',
    keyTakeawayKo: '후행성 지표이므로 거래량 수반 여부와 경기 펀더멘털을 함께 확인하여 휩소(속임수)를 걸러내야 합니다.',
    keyTakeawayEn: 'Confirm with volume spikes to filter out lagging whipsaw false signals.',
    relatedCalculatorUrl: '/tools/escape-price-calculator',
    relatedCalculatorLabelKo: '상승 추세 탈출 단가 계산기',
    relatedTickers: ['SPY', '005930']
  },
  {
    slug: 'dead-cross',
    termKo: '데드크로스 (Death Cross)',
    termEn: 'Death Cross',
    termJa: 'デッドクロス (Death Cross)',
    termZh: '死叉 / 死亡交叉 (Death Cross)',
    category: 'trading',
    formula: '신호: 단기 이동평균선(50일)이 장기 이동평균선(200일)을 위에서 아래로 하향 이탈',
    formulaDescriptionKo: '단기 매수세가 급격히 약화되며 장기 지지선을 무너뜨려 본격적인 하락장 진입을 예고하는 위험 신호입니다.',
    descriptionKo: '데드크로스는 단기 이동평균선이 장기 이동평균선 밑으로 떨어지는 기술적 현상으로, 전형적인 약세장(베어마켓) 진입 신호입니다. 50일선이 200일선을 하향 돌파할 때 많은 헤지펀드가 자동 손절매나 헤지 숏 포지션을 실행하므로 주가 하락이 가속화될 수 있습니다.',
    descriptionEn: 'A death cross happens when a short-term moving average crosses below a long-term moving average, signaling sustained bearish momentum.',
    descriptionJa: 'デッドクロスは、短期移動平均線が長期移動平均線を上から下に割り込む現象で、下落トレンドへの転換を示唆します。',
    descriptionZh: '死亡交叉是指短期均线向下击穿长期均线，预示着中长期熊市下行风险加剧。',
    keyTakeawayKo: '데드크로스 발생 시 즉각적인 비중 축소 또는 헤지 포지션 수립으로 계좌 잔고를 방어해야 합니다.',
    keyTakeawayEn: 'De-risk or establish protective hedges promptly upon death cross confirmations.',
    relatedCalculatorUrl: '/tools/escape-price-calculator',
    relatedCalculatorLabelKo: '하락장 평단가 탈출 계산기',
    relatedTickers: ['SPY', 'QQQ']
  },
  {
    slug: 'compound-interest',
    termKo: '복리 효과 (Compound Interest)',
    termEn: 'Compound Interest Effect',
    termJa: '複利効果 (Compound Interest)',
    termZh: '复利效应 (Compound Interest)',
    category: 'profitability',
    formula: '원리금 합계 = 원금 × (1 + 수익률)^기간',
    formulaDescriptionKo: '원금뿐만 아니라 발생한 이자/수익에도 다시 이자가 붙어 시간이 지날수록 자산이 눈덩이처럼 기하급수적으로 증식하는 원리입니다.',
    descriptionKo: '아인슈타인이 "세계 8대 불가사의"라고 칭송한 복리 효과는 초기에는 완만하게 증가하지만 일정 시간이 지나면 기하급수적으로 폭발하는 성질을 갖습니다. 매년 지급받은 배당금을 소비하지 않고 다시 주식을 재매수하는 배당 재투자(DRIP) 전략은 복리 엔진의 효율을 극대화하는 최고의 방법입니다.',
    descriptionEn: 'Compound interest generates earnings not only on initial principal but on previously accumulated interest, yielding exponential growth.',
    descriptionJa: '複利効果とは、元本だけでなく発生した利息にも再び利息がつくことで、時間が経つほど雪だるま式に資産が増える現象です。',
    descriptionZh: '复利效应是指投资所得收益继续并入本金生息，随时间推移资产呈现指数级爆炸增长的规律。',
    keyTakeawayKo: '복리의 가장 위대한 조력자는 "시간"이므로 하루라도 일찍 투자를 시작하고 지속하는 것이 핵심입니다.',
    keyTakeawayEn: 'Time is compounding\'s greatest fuel; starting earlier yields dramatically superior wealth.',
    relatedCalculatorUrl: '/tools/cagr-calculator',
    relatedCalculatorLabelKo: '복리 계산기 바로가기',
    relatedTickers: ['VOO', 'SCHD']
  },
  {
    slug: 'drip-dividend-reinvestment',
    termKo: '배당 재투자 프로그램 (DRIP)',
    termEn: 'DRIP (Dividend Reinvestment Plan)',
    termJa: '配当再投資 (DRIP)',
    termZh: '股息再投资 (DRIP)',
    category: 'dividend',
    formula: 'DRIP 수식: 수령 세후 배당금으로 매 분기 즉시 동일 종목 추가 자동 매수',
    formulaDescriptionKo: '지급받은 배당금을 인출하지 않고 즉시 해당 종목의 주식을 추가 매수하여 보유 주식 수를 복리로 늘려가는 전략입니다.',
    descriptionKo: 'DRIP(Dividend Reinvestment Plan)은 배당금을 현금으로 받아 쓰지 않고 자동으로 해당 주식의 추가 주수를 사들이는 제도입니다. 주가가 하락했을 때는 배당금으로 더 많은 주식을 저렴하게 살 수 있어 평단가가 낮아지고, 배당락 회복 후에는 더 커진 주식 수 덕분에 다음 분기 배당금이 폭증하는 선순환 복리 엔진을 만듭니다.',
    descriptionEn: 'A Dividend Reinvestment Plan automatically re-allocates cash dividends into purchasing additional fractional or whole shares.',
    descriptionJa: '配当再投資（DRIP）は、受け取った配当金を使って自動的に同じ株式を買い増し、複利で持ち株数を増やしていく仕組みです。',
    descriptionZh: '股息再投资计划（DRIP）是将收到的现金分红自动重新购买原公司股票，实现持股数量的滚雪球复利增长。',
    keyTakeawayKo: '20년간 DRIP을 가동한 계좌는 단순 현금 수령 계좌 대비 3배~5배 이상의 최종 자산 격차를 만듭니다.',
    keyTakeawayEn: 'DRIP portfolios outperform cash-harvesting portfolios by 3-5x over a 20-year horizon.',
    relatedCalculatorUrl: '/tools/dividend-tax-calculator',
    relatedCalculatorLabelKo: 'DRIP 배당 재투자 시뮬레이터',
    relatedTickers: ['SCHD', 'O', 'KO']
  },
  {
    slug: 'etf-exchange-traded-fund',
    termKo: 'ETF 상장지수펀드 (Exchange Traded Fund)',
    termEn: 'Exchange Traded Fund (ETF)',
    termJa: 'ETF (上場投資信託)',
    termZh: 'ETF (交易所交易基金)',
    category: 'trading',
    formula: '특징: 펀드의 분산 투자 장점 + 개별 주식의 실시간 거래 편의성 결합',
    formulaDescriptionKo: '특정 주가 지수나 테마의 성과를 추종하도록 설계되어 증권시장에 상장되어 주식처럼 실시간 매매할 수 있는 인덱스 펀드입니다.',
    descriptionKo: 'ETF는 지수를 추종하는 인덱스 펀드를 주식처럼 시장에 상장시켜 실시간으로 1주 단위로 사고팔 수 있게 만든 금융상품입니다. 단 1주만 매수해도 S&P 500(500개 기업), KOSPI 200(200개 기업) 등 수백 개 우량 기업에 즉시 분산 투자하는 효과를 누릴 수 있으며, 개별 종목 파산 리스크를 원천 차단합니다.',
    descriptionEn: 'An Exchange Traded Fund (ETF) is a pooled investment security that tracks an index and can be bought and sold like regular stock.',
    descriptionJa: 'ETFは、指数に連動するように運用され、証券取引所でリアルタイムに売買できる投資信託です。高い分散効果が特徴です。',
    descriptionZh: '交易型开放式指数基金（ETF）是一种跟踪特定指数并在证券交易所挂牌上市实时交易的基金，兼具分散与流动性。',
    keyTakeawayKo: '개별 기업 분석에 시간이 부족한 직장인에게는 S&P 500 및 나스닥 ETF 모아가기가 최선의 정답입니다.',
    keyTakeawayEn: 'Broad-market index ETFs represent the optimal default for busy retail investors.',
    relatedCalculatorUrl: '/tools/cagr-calculator',
    relatedCalculatorLabelKo: 'ETF 복리 투자 수익률 계산기',
    relatedTickers: ['SPY', 'QQQ', 'SCHD']
  },
  {
    slug: 'reit-real-estate-investment-trust',
    termKo: '리츠 (REITs / 부동산투자회사)',
    termEn: 'REITs (Real Estate Investment Trusts)',
    termJa: 'REIT (不動産投資信託)',
    termZh: 'REITs (不动产投资信托基金)',
    category: 'dividend',
    formula: '의무 규정: 배당가능이익의 90% 이상을 주주에게 의무 배당 시 법인세 면제',
    formulaDescriptionKo: '다수의 투자자로부터 모은 자금으로 상업용 빌딩, 물류센터, 통신탑 등에 투자하고 임대수익의 90% 이상을 배당하는 회사입니다.',
    descriptionKo: '리츠(REITs)는 다수의 투자자로부터 자금을 모아 오피스, 물류센터, 쇼핑몰, 데이터센터 등 고가의 상업용 부동산에 투자한 후 임대료 수익의 90% 이상을 주주들에게 배당금으로 지급하는 법인입니다. 주식 시장에서 소액으로 건물주가 되어 매월 또는 매 분기 안정적인 월세 배당을 챙길 수 있는 대표적인 인컴 자산입니다.',
    descriptionEn: 'REITs own and operate income-producing commercial real estate, required by law to distribute 90%+ of taxable income as dividends.',
    descriptionJa: 'REIT（不動産投資信託）は、多くの投資家から集めた資金で不動産を保有・運用し、賃료収入の9割以上を配当として還元する法人です。',
    descriptionZh: '房地产投资信托（REITs）通过将可租借不动产证券化，依法将90%以上的可纳税利润分配给投资者以享受税收减免。',
    keyTakeawayKo: '리얼티인컴(O) 같은 월배당 리츠는 금리 인하기에 조달 비용 감소와 배당 매력 상승으로 큰 수혜를 입습니다.',
    keyTakeawayEn: 'Monthly paying REITs like Realty Income (O) benefit strongly during rate-cutting cycles.',
    relatedCalculatorUrl: '/tools/dividend-tax-calculator',
    relatedCalculatorLabelKo: '리츠 월배당 세금 & 수익 계산기',
    relatedTickers: ['O', 'AMT', 'PLD']
  },
  {
    slug: 'dividend-cut',
    termKo: '배당 삭감 (Dividend Cut)',
    termEn: 'Dividend Cut',
    termJa: '減配 (Dividend Cut)',
    termZh: '削减股息 / 降配 (Dividend Cut)',
    category: 'dividend',
    formula: '경고 신호: 배당성향 100% 초과 + 잉여현금흐름(FCF) 적자 전환',
    formulaDescriptionKo: '기업의 경영 실적 악화나 유동성 위기로 인해 기존에 지급하던 주당 배당금을 줄이거나 지급을 중단하는 조치입니다.',
    descriptionKo: '배당 삭감은 배당 투자자에게 가장 치명적인 악재입니다. 배당금이 줄어들면 현금 흐름 수익률이 급감할 뿐만 아니라, 배당을 노리고 진입했던 대규모 기관 및 인컴 펀드 자금이 일제히 이탈하면서 주가가 단기간에 20%~40% 이상 폭락하는 이중 타격을 받게 됩니다.',
    descriptionEn: 'A dividend cut occurs when a company decreases its per-share dividend payout, frequently triggering massive stock selloffs.',
    descriptionJa: '減配とは、企業が業績悪化などを理由に配当金額を引き下げることです。機関投資家の離脱を招き株価急落につながります。',
    descriptionZh: '削减股息是上市公司减少每股派息额度的行为，通常会导致追求分红的机构资金恐慌性出逃并引发股价崩盘。',
    keyTakeawayKo: '배당성향이 비정상적으로 높고 부채가 급증하는 종목은 배당 삭감 신호이므로 사전에 비중을 정리해야 합니다.',
    keyTakeawayEn: 'Exit high-yielding stocks displaying unsustainable payout ratios and deteriorating FCF.',
    relatedCalculatorUrl: '/tools/dividend-tax-calculator',
    relatedCalculatorLabelKo: '배당 지속가능성 진단 계산기',
    relatedTickers: ['INTC', 'MMM']
  },
  {
    slug: 'liquidity-trap',
    termKo: '유동성 함정 (Liquidity Trap)',
    termEn: 'Liquidity Trap',
    termJa: '流動性の罠 (Liquidity Trap)',
    termZh: '流动性陷阱 (Liquidity Trap)',
    category: 'macro',
    formula: '현상: 중앙은행의 금리 인하에도 소비와 투자 불응 → 현금 보유 선호',
    formulaDescriptionKo: '중앙은행이 금리를 0% 수준으로 낮추고 유동성을 대거 공급해도 경제 주체들의 불안으로 돈이 돌지 않는 경기 침체 상태입니다.',
    descriptionKo: '유동성 함정은 케인스가 제시한 개념으로, 통화 당국이 경기 부양을 위해 기준금리를 극도로 낮추고 통화 공급을 늘려도 시장 참여자들의 미래 비관론 때문에 소비와 투자가 늘지 않고 돈이 단기 금융상품이나 현금으로만 잠겨 있는 상태를 의미합니다. 일본의 잃어버린 30년이 대표적 예시입니다.',
    descriptionEn: 'A liquidity trap is a macroeconomic condition where interest rates are near zero yet consumers and firms hoard cash instead of investing.',
    descriptionJa: '流動性の罠は、金利が極めて低い水準にあっても、将来不安から投資や消費が増加せず景気浮揚効果が得られない状態です。',
    descriptionZh: '流动性陷阱是指央行无论如何降息增发货币，企业和居民依然选择持有现金而不愿消费投资的宏观停滞状态。',
    keyTakeawayKo: '유동성 함정기에는 현금 가치가 방어되는 반면 기업 이익은 정체되므로 배당 파이프라인의 견고성이 중요해집니다.',
    keyTakeawayEn: 'Focus on cash-rich monopolistic companies capable of preserving cash-flow during macro stagnation.',
    relatedCalculatorUrl: '/tools/cagr-calculator',
    relatedCalculatorLabelKo: '자산 보존 시뮬레이터',
    relatedTickers: ['TLT', 'GLD']
  },
  {
    slug: 'share-buyback',
    termKo: '자사주 매입 및 소각 (Share Buyback / Retirement)',
    termEn: 'Share Buybacks and Cancellation',
    termJa: '自社株買い・消却 (Share Buybacks)',
    termZh: '股份回购与注销 (Share Buybacks)',
    category: 'profitability',
    formula: '효과: 유통 주식 수 감소 → EPS(주당순이익) 및 BPS 상승 → 주가 부양',
    formulaDescriptionKo: '기업이 벌어들인 잉여 현금으로 시장에서 자기 회사 주식을 사들여 영구 소각함으로써 주주 가치를 높이는 환원 방식입니다.',
    descriptionKo: '자사주 매입 및 소각은 배당금 지급과 함께 미국 시장에서 가장 보편적인 주주환원 방식입니다. 기업이 자사주를 사들여 소각하면 전체 주식 수가 영구히 줄어들기 때문에, 기업 이익이 늘지 않아도 1주당 순이익(EPS)이 자동으로 상승합니다. 배당소득세(15.4%)가 부과되지 않고 주가 상승을 통해 주주에게 보상하므로 절세 측면에서도 매우 유리합니다.',
    descriptionEn: 'Share repurchases reduce outstanding share count, automatically enhancing EPS and delivering tax-efficient capital appreciation.',
    descriptionJa: '自社株買い・消却は、市場の流通株式数を減らすことで1株当たり利益（EPS）を引き上げ、株価を下支えする株主還元策です。',
    descriptionZh: '股票回购注销减少了市场流通股总量，直接提高每股收益（EPS），具有相较现金分红无需扣除股息税的节税优势。',
    keyTakeawayKo: '애플(AAPL)은 매년 수백억 달러 규모의 자사주 소각을 단행하여 주가의 장기 우상향을 이끌어왔습니다.',
    keyTakeawayEn: 'Apple demonstrates how systematic buybacks serve as a relentless structural engine for share appreciation.',
    relatedCalculatorUrl: '/tools/cagr-calculator',
    relatedCalculatorLabelKo: '주당순이익 복리 성장 계산기',
    relatedTickers: ['AAPL', 'GOOGL', 'NVDA']
  },
  {
    slug: 'circuit-breaker',
    termKo: '서킷브레이커 (Circuit Breaker)',
    termEn: 'Circuit Breaker',
    termJa: 'サーキットブレーカー (Circuit Breaker)',
    termZh: '熔断机制 (Circuit Breaker)',
    category: 'trading',
    formula: '발동 조건: 주가 지수가 전일 대비 8%(1단계), 15%(2단계), 20%(3단계 당일 마감) 급락 시',
    formulaDescriptionKo: '주식 시장이 단기간에 비이성적으로 폭락할 때 투자자들에게 냉정함을 찾을 시간을 주기 위해 매매를 일시 중단시키는 제도입니다.',
    descriptionKo: '서킷브레이커(Circuit Breaker)는 전기 회로 차단기에서 유래한 제도로, 시장 지수가 사전에 정해진 기준 이상으로 폭락할 경우 거래소 전체의 주식 매매를 강제로 20분간 전면 중단시키는 안전장치입니다. 1987년 블랙 먼데이 이후 도입되었으며, 패닉 셀링의 연쇄 반응을 차단하는 역할을 합니다.',
    descriptionEn: 'Market circuit breakers temporarily halt trading across all exchanges when benchmark indices experience drastic percentage drops.',
    descriptionJa: 'サーキットブレーカー制度は、株価指数が急落した際に取引を一時停止させ、パニック売りを沈静化させる安全装置です。',
    descriptionZh: '熔断机制是在股指发生剧烈恐慌性暴跌时，交易所自动暂停全部交易以恢复市场理性的冷却机制。',
    keyTakeawayKo: '서킷브레이커가 발동된 공포의 날은 역사적으로 장기 가치 투자자에게 평생에 몇 번 없는 최고의 저가 매수 기회였습니다.',
    keyTakeawayEn: 'Circuit breaker days historically represented legendary generational buying opportunities for long-term investors.',
    relatedCalculatorUrl: '/tools/escape-price-calculator',
    relatedCalculatorLabelKo: '폭락장 평단가 탈출 계산기',
    relatedTickers: ['SPY', '005930']
  },
  {
    slug: 'sidecar',
    termKo: '사이드카 (Sidecar)',
    termEn: 'Sidecar',
    termJa: 'サイドカー (Sidecar)',
    termZh: '临时停牌 / 缓冲限制 (Sidecar)',
    category: 'trading',
    formula: '발동: 선물 가격이 전일 종가 대비 5% 이상 변동 상태가 1분간 지속될 때',
    formulaDescriptionKo: '선물 시장의 급격한 변동이 현물 주식 시장으로 전이되는 것을 막기 위해 프로그램 매매 호가 효력을 5분간 정지하는 제도입니다.',
    descriptionKo: '사이드카는 선물 시장 가격이 전일 대비 5%(코스피) 또는 6%(코스닥) 이상 급등락하여 1분 이상 지속될 때, 프로그램 매매 호가의 효력을 5분 동안 정지시키는 제도입니다. 서킷브레이커보다 한 단계 낮은 경고 단계로, 프로그램 매매로 인한 현물 시장의 급변을 완충합니다. 1일 1회만 발동됩니다.',
    descriptionEn: 'A sidecar temporarily pauses automated program trading orders for 5 minutes when index futures swing violently.',
    descriptionJa: 'サイドカーは、先物市場の急変動が株式現物市場に波及するのを防ぐため、プログラム売買の注文効力を5分間停止する制度です。',
    descriptionZh: '股指期货价格剧烈波动时，交易所暂停程序化交易委托5分钟以平抑现货市场波动的缓冲机制。',
    keyTakeawayKo: '사이드카 발동은 당일 극심한 단타 수급 변동성을 의미하므로 섣부른 뇌동매매를 삼가야 합니다.',
    keyTakeawayEn: 'Refrain from impulsive trades during sidecar triggers due to chaotic intraday volatility.',
    relatedCalculatorUrl: '/tools/escape-price-calculator',
    relatedCalculatorLabelKo: '단타 손실 회복 계산기',
    relatedTickers: ['005930', '000660']
  },
  {
    slug: 'yield-curve-inversion',
    termKo: '장단기 금리역전 (Yield Curve Inversion)',
    termEn: 'Yield Curve Inversion',
    termJa: '長短金利の逆転 (イールドカーブ逆転)',
    termZh: '收益率曲线倒挂 (Yield Curve Inversion)',
    category: 'macro',
    formula: '지표: 미국 국채 10년물 금리 < 미국 국채 2년물 금리',
    formulaDescriptionKo: '만기가 긴 장기 채권 금리가 단기 채권 금리보다 낮아지는 비정상적 현상으로, 역사상 가장 정확한 경기 침체 선행 지표입니다.',
    descriptionKo: '장단기 금리역전은 만기가 긴 10년물 국채 금리가 단기인 2년물 국채 금리보다 낮아지는 현상입니다. 정상적인 경제에서는 장기 투자에 따른 불확실성 프리미엄 때문에 장기 금리가 더 높아야 하지만, 시장 참여자들이 미래 경기 침체를 확신하고 장기 채권을 사들이면서 장기 금리가 급락하여 역전이 발생합니다. 지난 50년간 거의 모든 경기 침체를 선행 예고했습니다.',
    descriptionEn: 'An inverted yield curve occurs when short-term treasury yields exceed long-term yields, acting as a premier recession predictor.',
    descriptionJa: '長短金利逆転は、2年債利回りが10年債利回りを上回る現象で、歴史上最も信頼性の高い景気後退の先行指標です。',
    descriptionZh: '短期国债收益率反超长期国债收益率的异常现象，被公认为过去半个世纪预测经济衰退最精准的先行指标。',
    keyTakeawayKo: '금리역전 자체보다, 역전이 해소되며 정상화되는 시점에 실제 경기 침체와 주가 조정이 본격화되는 패턴이 잦습니다.',
    keyTakeawayEn: 'Major stock market corrections historically cluster around the subsequent re-steepening un-inversion phase.',
    relatedCalculatorUrl: '/tools/cagr-calculator',
    relatedCalculatorLabelKo: '경기 사이클 자산배분 계산기',
    relatedTickers: ['TLT', 'SHY', 'SPY']
  },
  {
    slug: 'drawdown-mdd',
    termKo: 'MDD (최대 낙폭 / Maximum Drawdown)',
    termEn: 'Maximum Drawdown (MDD)',
    termJa: '最大下落率 (MDD)',
    termZh: '最大回撤 (MDD)',
    category: 'trading',
    formula: 'MDD = (특정 기간 중 최저점 가격 - 최고점 가격) / 최고점 가격 × 100 (%)',
    formulaDescriptionKo: '투자를 진행하는 동안 고점 대비 계좌 잔고가 최대 몇 %까지 추락했는지를 측정하는 고통 지수이자 리스크 측정치입니다.',
    descriptionKo: 'MDD(Maximum Drawdown)는 투자 포트폴리오가 역사적 최고점에서 최저점까지 얼마나 떨어졌는지를 백분율로 나타낸 값입니다. 수익률이 아무리 높아도 MDD가 -50%를 넘어가면 대부분의 개인 투자자는 공포에 질려 바닥에서 투매(손절)하게 됩니다. 진정한 장기 복리 투자를 달성하기 위해서는 MDD를 통제할 수 있는 분산 투자가 필수적입니다.',
    descriptionEn: 'Maximum Drawdown (MDD) calculates the peak-to-trough decline of an investment before a new peak is attained.',
    descriptionJa: 'MDD（最大下落率）は、過去最高値から最安値までの下落幅を示し、投資家が耐えるべき心理的リスクの深さを表します。',
    descriptionZh: '最大回撤（MDD）衡量特定时间段内投资组合从峰值跌至谷底的最大跌幅百分比，是评估抗风险韧性的关键。',
    keyTakeawayKo: '-50%의 손실을 복구하려면 +100%의 수익률이 필요하므로 MDD 방어가 투자 성공의 전부입니다.',
    keyTakeawayEn: 'A 50% loss requires a 100% gain just to break even; controlling MDD is paramount.',
    relatedCalculatorUrl: '/tools/escape-price-calculator',
    relatedCalculatorLabelKo: '손실 복구 탈출 수익률 계산기',
    relatedTickers: ['QQQ', 'TQQQ', 'SPY']
  },
  {
    slug: 'sharpe-ratio',
    termKo: '샤프 지수 (Sharpe Ratio)',
    termEn: 'Sharpe Ratio',
    termJa: 'シャープレシオ (Sharpe Ratio)',
    termZh: '夏普比率 (Sharpe Ratio)',
    category: 'profitability',
    formula: 'Sharpe = (포트폴리오 수익률 - 무위험 이자율) / 포트폴리오 변동성(표준편차)',
    formulaDescriptionKo: '1단위의 위험(변동성)을 감수했을 때 무위험 자산 대비 얼마의 초과 수익을 얻었는지를 나타내는 위험 조정 성과 지표입니다.',
    descriptionKo: '노벨경제학상 수상자 윌리엄 샤프가 고안한 샤프 지수는 투자자가 감수한 위험 대비 성과를 측정합니다. 샤프 지수가 1.0 이상이면 양호하고, 2.0 이상이면 매우 뛰어난 전략으로 평가받습니다. 단순히 수익률만 높은 포트폴리오보다 변동성이 적으면서 꾸준한 수익을 내는 포트폴리오가 훨씬 높은 샤프 지수를 기록합니다.',
    descriptionEn: 'The Sharpe ratio measures risk-adjusted return by dividing excess return over the risk-free rate by overall volatility.',
    descriptionJa: 'シャープレシオは、取ったリスクに対してどれだけの超過リターンを得られたかを測る投資効率指標です。',
    descriptionZh: '夏普比率衡量每承担一单位总风险所获得的超额投资回报，是衡量投资组合真实收益质量的标尺。',
    keyTakeawayKo: '수익률이 20%라도 변동성이 40%라면, 수익률 12%에 변동성 8%인 자산배분 전략보다 위험 대비 비효율적입니다.',
    keyTakeawayEn: 'Prioritize higher risk-adjusted efficiency rather than chasing raw unhedged returns.',
    relatedCalculatorUrl: '/tools/cagr-calculator',
    relatedCalculatorLabelKo: '자산 배분 샤프 지수 계산기',
    relatedTickers: ['SPY', 'QQQ']
  }
];

export const GLOSSARY_CATEGORIES = [
  { id: 'all', labelKo: '전체 보기', labelEn: 'All', labelJa: 'すべて', labelZh: '全部' },
  { id: 'valuation', labelKo: '가치평가 지표', labelEn: 'Valuation', labelJa: '株価指標', labelZh: '估值指标' },
  { id: 'profitability', labelKo: '수익성 & 현금흐름', labelEn: 'Profitability', labelJa: '収益性・CF', labelZh: '盈利与现金流' },
  { id: 'dividend', labelKo: '배당 & 인컴', labelEn: 'Dividends', labelJa: '配当・インカム', labelZh: '分红与股息' },
  { id: 'tax', labelKo: '세금 & 계좌 전략', labelEn: 'Tax Strategy', labelJa: '税金・非課税', labelZh: '税务与账户' },
  { id: 'trading', labelKo: '실전 매매 & 호가', labelEn: 'Trading & Orders', labelJa: '取引・売買', labelZh: '交易与订单' },
  { id: 'macro', labelKo: '거시경제 & 금리', labelEn: 'Macroeconomics', labelJa: 'マクロ経済・金利', labelZh: '宏观经济与利率' }
] as const;
