export interface RealEstatePreset {
  slug: string;
  name: string;
  nameEn: string;
  description: string;
  locationTag: string;
  purchasePrice: number; // 매매가 (원)
  deposit: number; // 보증금 (원)
  monthlyRent: number; // 월세 (원)
  loanAmount: number; // 대출금 (원)
  loanInterestRate: number; // 연 대출금리 (%)
  acquisitionTaxRate: number; // 취득세율 (%)
  annualMaintenanceExpense: number; // 연간 재산세/관리유지비 (원)
  seoKeywords: string[];
}

export const REAL_ESTATE_PRESETS: RealEstatePreset[] = [
  {
    slug: 'gangnam-office',
    name: '강남 테헤란로 프라임 오피스',
    nameEn: 'Gangnam Teheran-ro Prime Office',
    description: '대한민국 IT·금융 중심지 테헤란로 대형 빌딩 임대 수익률 시뮬레이션',
    locationTag: '강남구 역삼동',
    purchasePrice: 1500000000,
    deposit: 100000000,
    monthlyRent: 6500000,
    loanAmount: 900000000,
    loanInterestRate: 4.2,
    acquisitionTaxRate: 4.6,
    annualMaintenanceExpense: 4800000,
    seoKeywords: ['강남 오피스 임대수익률', '테헤란로 사무실 월세 계산기', '상가건물 수익률 계산기', '부동산 ROE 계산'],
  },
  {
    slug: 'yeouido-penthouse',
    name: '여의도 금융가 펜트하우스',
    nameEn: 'Yeouido Financial District Penthouse',
    description: '여의도 한강뷰 최고급 하이엔드 주거/오피스텔 임대 수익률 분석',
    locationTag: '영등포구 여의도동',
    purchasePrice: 2500000000,
    deposit: 200000000,
    monthlyRent: 11000000,
    loanAmount: 1500000000,
    loanInterestRate: 4.0,
    acquisitionTaxRate: 4.6,
    annualMaintenanceExpense: 7200000,
    seoKeywords: ['여의도 펜트하우스 월세', '고급주거 임대수익률', '여의도 오피스텔 수익률', '부동산 Cap Rate 계산'],
  },
  {
    slug: 'pangyo-studio',
    name: '판교 밸리 개발자 스튜디오',
    nameEn: 'Pangyo Techno Valley Studio',
    description: '판교 테크노밸리 IT 직주근접 원룸/오피스텔 공실 없는 월세 투자',
    locationTag: '성남시 분당구 삼평동',
    purchasePrice: 350000000,
    deposit: 30000000,
    monthlyRent: 1400000,
    loanAmount: 200000000,
    loanInterestRate: 4.5,
    acquisitionTaxRate: 4.6,
    annualMaintenanceExpense: 1200000,
    seoKeywords: ['판교 오피스텔 월세 수익률', '원룸 임대수익률 계산기', '판교 테크노밸리 월세', '소액 부동산 투자'],
  },
  {
    slug: 'seongsu-atelier',
    name: '성수 아뜰리에 팝업 상가',
    nameEn: 'Seongsu Atelier Pop-up Space',
    description: 'MZ 핫플레이스 성수동 카페거리 트렌디 상가 임대 수익 시뮬레이션',
    locationTag: '성동구 성수동2가',
    purchasePrice: 800000000,
    deposit: 50000000,
    monthlyRent: 3800000,
    loanAmount: 500000000,
    loanInterestRate: 4.3,
    acquisitionTaxRate: 4.6,
    annualMaintenanceExpense: 2400000,
    seoKeywords: ['성수동 상가 임대수익률', '카페 상가 월세 계산기', '성수동 부동산 투자', '상가 Cap Rate'],
  },
  {
    slug: 'hannam-hillside',
    name: '한남 힐사이드 럭셔리 레지던스',
    nameEn: 'Hannam Hillside Luxury Residence',
    description: '대한민국 최고 부촌 한남동 외교관/외국인 렌트 임대 수익률',
    locationTag: '용산구 한남동',
    purchasePrice: 3000000000,
    deposit: 300000000,
    monthlyRent: 13000000,
    loanAmount: 1800000000,
    loanInterestRate: 3.9,
    acquisitionTaxRate: 4.6,
    annualMaintenanceExpense: 8400000,
    seoKeywords: ['한남동 렌트 수익률', '외국인 렌트 월세 계산기', '고급빌라 임대수익률', '한남동 부동산'],
  },
  {
    slug: 'songdo-central',
    name: '송도 센트럴 스마트 오피스텔',
    nameEn: 'Songdo Central Smart Officetel',
    description: '송도 국제도시 바이오 클러스터 배후 주거 월세 수익 모델',
    locationTag: '인천 연수구 송도동',
    purchasePrice: 280000000,
    deposit: 20000000,
    monthlyRent: 1100000,
    loanAmount: 170000000,
    loanInterestRate: 4.6,
    acquisitionTaxRate: 4.6,
    annualMaintenanceExpense: 960000,
    seoKeywords: ['송도 오피스텔 수익률', '송도국제도시 월세 계산기', '소액 오피스텔 투자', '임대사업자 세금'],
  },
  {
    slug: 'mapo-creative',
    name: '마포 크리에이티브 공유오피스',
    nameEn: 'Mapo Creative Shared Office',
    description: '홍대·합정 크리에이터 배후 공유형 작업실 및 스튜디오 임대',
    locationTag: '마포구 서교동',
    purchasePrice: 450000000,
    deposit: 40000000,
    monthlyRent: 1900000,
    loanAmount: 280000000,
    loanInterestRate: 4.4,
    acquisitionTaxRate: 4.6,
    annualMaintenanceExpense: 1500000,
    seoKeywords: ['마포 공유오피스 수익률', '홍대 스튜디오 임대료', '공유오피스 창업 수익', '작업실 월세'],
  },
  {
    slug: 'busan-marinecity',
    name: '부산 해운대 마린시티 뷰',
    nameEn: 'Busan Haeundae Marine City View',
    description: '해운대 오션뷰 조망 프리미엄 레지던스 휴양/임대 하이브리드 수익',
    locationTag: '부산 해운대구 우동',
    purchasePrice: 1200000000,
    deposit: 100000000,
    monthlyRent: 5200000,
    loanAmount: 700000000,
    loanInterestRate: 4.3,
    acquisitionTaxRate: 4.6,
    annualMaintenanceExpense: 3800000,
    seoKeywords: ['해운대 마린시티 월세', '부산 오피스텔 임대수익률', '오션뷰 레지던스 수익', '해운대 부동산'],
  },
  {
    slug: 'small-apartment-yield',
    name: '수도권 소형 아파트 월세 투자',
    nameEn: 'Small Apartment Monthly Rent Investment',
    description: '안정적인 1~2인 가구 타깃 역세권 소형 아파트 월세 포트폴리오',
    locationTag: '수도권 역세권',
    purchasePrice: 500000000,
    deposit: 50000000,
    monthlyRent: 1800000,
    loanAmount: 300000000,
    loanInterestRate: 4.2,
    acquisitionTaxRate: 1.1,
    annualMaintenanceExpense: 1400000,
    seoKeywords: ['소형아파트 월세 수익률', '아파트 임대사업자 계산기', '역세권 아파트 월세', '부동산 갭투자 vs 월세'],
  },
  {
    slug: 'commercial-building-cap',
    name: '꼬마빌딩 근생 통임대 수익률',
    nameEn: 'Commercial Mini-Building Whole Lease',
    description: '근린생활시설 꼬마빌딩 전층 임대 및 레버리지 극대화 분석',
    locationTag: '서울 주요 상권',
    purchasePrice: 4000000000,
    deposit: 400000000,
    monthlyRent: 18000000,
    loanAmount: 2500000000,
    loanInterestRate: 4.1,
    acquisitionTaxRate: 4.6,
    annualMaintenanceExpense: 9600000,
    seoKeywords: ['꼬마빌딩 수익률 계산기', '근생 빌딩 임대수익률', '서울 꼬마빌딩 투자', '부동산 레버리지 ROE'],
  },
];

export function getRealEstatePreset(slug: string): RealEstatePreset | undefined {
  return REAL_ESTATE_PRESETS.find((p) => p.slug === slug);
}
