export type ApiChannel = 'APP' | 'SITE';
export type ApiAuthMode = 'PUBLIC' | 'SESSION' | 'ADMIN';
export type ApiHttpMethod = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';
export type ApiIntegrityPolicy = 'NONE' | 'RISK_BASED' | 'REQUIRED';
export type ApiRouteAvailability = 'TARGET' | 'LIVE';

export interface ChannelRouteDefinition {
  readonly channel: ApiChannel;
  readonly method: ApiHttpMethod;
  readonly pathTemplate: string;
  readonly authMode: ApiAuthMode;
  readonly scope: string;
  readonly idempotencyRequired: boolean;
  readonly csrfRequired: boolean;
  readonly integrityPolicy: ApiIntegrityPolicy;
  readonly economyCommand: string | null;
  readonly sharedReadOnly: boolean;
  readonly availability: ApiRouteAvailability;
  readonly legacyPath: string | null;
}

/**
 * Canonical target public-route inventory for the App v2 and Site v1 BFFs.
 * App rows are derived from docs/mobile-api-contract.json (179 v1 endpoints) and
 * preserve legacyPath only as migration evidence. Site rows are browser-direct
 * routes proven in current source and verified against backend/mobile contracts.
 * TARGET means the contract is approved but the public BFF file is introduced in Task 3.
 */
export const CHANNEL_API_ROUTES: readonly ChannelRouteDefinition[] = [
  {
    channel: "APP",
    method: "DELETE",
    pathTemplate: "/app-api/v2/account",
    authMode: "SESSION",
    scope: "app.account.write",
    idempotencyRequired: false,
    csrfRequired: true,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/account",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/account/identities",
    authMode: "SESSION",
    scope: "app.account.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/account/identities",
  },
  {
    channel: "APP",
    method: "DELETE",
    pathTemplate: "/app-api/v2/account/identities/:id",
    authMode: "SESSION",
    scope: "app.account.write",
    idempotencyRequired: false,
    csrfRequired: true,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/account/identities/:id",
  },
  {
    channel: "APP",
    method: "POST",
    pathTemplate: "/app-api/v2/account/identities/:provider/link",
    authMode: "SESSION",
    scope: "app.account.write",
    idempotencyRequired: false,
    csrfRequired: true,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/account/identities/:provider/link",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/account/security/events",
    authMode: "SESSION",
    scope: "app.account.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/account/security/events",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/account/security/sessions",
    authMode: "SESSION",
    scope: "app.account.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/account/security/sessions",
  },
  {
    channel: "APP",
    method: "DELETE",
    pathTemplate: "/app-api/v2/account/security/sessions/:id",
    authMode: "SESSION",
    scope: "app.account.write",
    idempotencyRequired: false,
    csrfRequired: true,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/account/security/sessions/:id",
  },
  {
    channel: "APP",
    method: "POST",
    pathTemplate: "/app-api/v2/account/security/sessions/revoke-others",
    authMode: "SESSION",
    scope: "app.account.write",
    idempotencyRequired: false,
    csrfRequired: true,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/account/security/sessions/revoke-others",
  },
  {
    channel: "APP",
    method: "POST",
    pathTemplate: "/app-api/v2/activity/events",
    authMode: "SESSION",
    scope: "app.activity.write",
    idempotencyRequired: false,
    csrfRequired: true,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/activity/events",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/admin/activity/logs",
    authMode: "ADMIN",
    scope: "app.admin.admin",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/admin/activity/logs",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/admin/activity/traffic",
    authMode: "ADMIN",
    scope: "app.admin.admin",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/admin/activity/traffic",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/admin/economy/ai-status",
    authMode: "ADMIN",
    scope: "app.admin.admin",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/admin/economy/ai-status",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/admin/me",
    authMode: "ADMIN",
    scope: "app.admin.admin",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/admin/me",
  },
  {
    channel: "APP",
    method: "POST",
    pathTemplate: "/app-api/v2/admin/security/sessions",
    authMode: "ADMIN",
    scope: "app.admin.admin",
    idempotencyRequired: false,
    csrfRequired: true,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/admin/security/sessions",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/admin/support/threads",
    authMode: "ADMIN",
    scope: "app.admin.admin",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/admin/support/threads",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/admin/support/threads/:id/messages",
    authMode: "ADMIN",
    scope: "app.admin.admin",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/admin/support/threads/:id/messages",
  },
  {
    channel: "APP",
    method: "POST",
    pathTemplate: "/app-api/v2/admin/support/threads/:id/messages",
    authMode: "ADMIN",
    scope: "app.admin.admin",
    idempotencyRequired: false,
    csrfRequired: true,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/admin/support/threads/:id/messages",
  },
  {
    channel: "APP",
    method: "PUT",
    pathTemplate: "/app-api/v2/admin/support/threads/:id/status",
    authMode: "ADMIN",
    scope: "app.admin.admin",
    idempotencyRequired: false,
    csrfRequired: true,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/admin/support/threads/:id/status",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/admin/users",
    authMode: "ADMIN",
    scope: "app.admin.admin",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/admin/users",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/admin/work",
    authMode: "ADMIN",
    scope: "app.admin.admin",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/admin/work",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/auth/:provider/authorize",
    authMode: "PUBLIC",
    scope: "app.auth.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/auth/:provider/authorize",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/auth/:provider/callback",
    authMode: "PUBLIC",
    scope: "app.auth.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/auth/:provider/callback",
  },
  {
    channel: "APP",
    method: "POST",
    pathTemplate: "/app-api/v2/auth/:provider/reauthentication",
    authMode: "SESSION",
    scope: "app.auth.write",
    idempotencyRequired: false,
    csrfRequired: true,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/auth/:provider/reauthentication",
  },
  {
    channel: "APP",
    method: "PUT",
    pathTemplate: "/app-api/v2/auth/consent",
    authMode: "PUBLIC",
    scope: "app.auth.write",
    idempotencyRequired: false,
    csrfRequired: true,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/auth/consent",
  },
  {
    channel: "APP",
    method: "POST",
    pathTemplate: "/app-api/v2/auth/local/login",
    authMode: "PUBLIC",
    scope: "app.auth.write",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/auth/local/login",
  },
  {
    channel: "APP",
    method: "POST",
    pathTemplate: "/app-api/v2/auth/local/password-reset/complete",
    authMode: "PUBLIC",
    scope: "app.auth.write",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/auth/local/password-reset/complete",
  },
  {
    channel: "APP",
    method: "POST",
    pathTemplate: "/app-api/v2/auth/local/password-reset/request",
    authMode: "PUBLIC",
    scope: "app.auth.write",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/auth/local/password-reset/request",
  },
  {
    channel: "APP",
    method: "POST",
    pathTemplate: "/app-api/v2/auth/local/register",
    authMode: "PUBLIC",
    scope: "app.auth.write",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/auth/local/register",
  },
  {
    channel: "APP",
    method: "POST",
    pathTemplate: "/app-api/v2/auth/local/verify-email",
    authMode: "PUBLIC",
    scope: "app.auth.write",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/auth/local/verify-email",
  },
  {
    channel: "APP",
    method: "POST",
    pathTemplate: "/app-api/v2/auth/logout",
    authMode: "SESSION",
    scope: "app.auth.write",
    idempotencyRequired: false,
    csrfRequired: true,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/auth/logout",
  },
  {
    channel: "APP",
    method: "POST",
    pathTemplate: "/app-api/v2/auth/mobile/handoff",
    authMode: "PUBLIC",
    scope: "app.auth.write",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/auth/mobile/handoff",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/auth/policy",
    authMode: "PUBLIC",
    scope: "app.auth.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/auth/policy",
  },
  {
    channel: "APP",
    method: "POST",
    pathTemplate: "/app-api/v2/auth/prelogin-session",
    authMode: "PUBLIC",
    scope: "app.auth.write",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/auth/prelogin-session",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/auth/providers",
    authMode: "PUBLIC",
    scope: "app.auth.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/auth/providers",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/auth/session",
    authMode: "SESSION",
    scope: "app.auth.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: true,
    availability: "TARGET",
    legacyPath: "/app-api/v1/auth/session",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/auth/viewer",
    authMode: "SESSION",
    scope: "app.auth.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/auth/viewer",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/bank/loans",
    authMode: "SESSION",
    scope: "app.bank.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/bank/loans",
  },
  {
    channel: "APP",
    method: "POST",
    pathTemplate: "/app-api/v2/bank/loans",
    authMode: "SESSION",
    scope: "app.bank.write",
    idempotencyRequired: true,
    csrfRequired: true,
    integrityPolicy: "RISK_BASED",
    economyCommand: "post:bank.loans",
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/bank/loans",
  },
  {
    channel: "APP",
    method: "POST",
    pathTemplate: "/app-api/v2/bank/loans/:id/repayments",
    authMode: "SESSION",
    scope: "app.bank.write",
    idempotencyRequired: true,
    csrfRequired: true,
    integrityPolicy: "RISK_BASED",
    economyCommand: "post:bank.loans.{id}.repayments",
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/bank/loans/:id/repayments",
  },
  {
    channel: "APP",
    method: "POST",
    pathTemplate: "/app-api/v2/bank/movements",
    authMode: "SESSION",
    scope: "app.bank.write",
    idempotencyRequired: true,
    csrfRequired: true,
    integrityPolicy: "RISK_BASED",
    economyCommand: "post:bank.movements",
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/bank/movements",
  },
  {
    channel: "APP",
    method: "POST",
    pathTemplate: "/app-api/v2/banking/bonds/:id/redeem",
    authMode: "SESSION",
    scope: "app.banking.write",
    idempotencyRequired: true,
    csrfRequired: true,
    integrityPolicy: "RISK_BASED",
    economyCommand: "post:banking.bonds.{id}.redeem",
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/banking/bonds/:id/redeem",
  },
  {
    channel: "APP",
    method: "POST",
    pathTemplate: "/app-api/v2/banking/bonds/purchase",
    authMode: "SESSION",
    scope: "app.banking.write",
    idempotencyRequired: true,
    csrfRequired: true,
    integrityPolicy: "RISK_BASED",
    economyCommand: "post:banking.bonds.purchase",
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/banking/bonds/purchase",
  },
  {
    channel: "APP",
    method: "POST",
    pathTemplate: "/app-api/v2/banking/borrow",
    authMode: "SESSION",
    scope: "app.banking.write",
    idempotencyRequired: true,
    csrfRequired: true,
    integrityPolicy: "RISK_BASED",
    economyCommand: "post:banking.borrow",
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/banking/borrow",
  },
  {
    channel: "APP",
    method: "POST",
    pathTemplate: "/app-api/v2/banking/claim-interest",
    authMode: "SESSION",
    scope: "app.banking.write",
    idempotencyRequired: true,
    csrfRequired: true,
    integrityPolicy: "NONE",
    economyCommand: "post:banking.claim-interest",
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/banking/claim-interest",
  },
  {
    channel: "APP",
    method: "POST",
    pathTemplate: "/app-api/v2/banking/deposit",
    authMode: "SESSION",
    scope: "app.banking.write",
    idempotencyRequired: true,
    csrfRequired: true,
    integrityPolicy: "RISK_BASED",
    economyCommand: "post:banking.deposit",
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/banking/deposit",
  },
  {
    channel: "APP",
    method: "POST",
    pathTemplate: "/app-api/v2/banking/repay",
    authMode: "SESSION",
    scope: "app.banking.write",
    idempotencyRequired: true,
    csrfRequired: true,
    integrityPolicy: "RISK_BASED",
    economyCommand: "post:banking.repay",
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/banking/repay",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/banking/standing",
    authMode: "SESSION",
    scope: "app.banking.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/banking/standing",
  },
  {
    channel: "APP",
    method: "POST",
    pathTemplate: "/app-api/v2/banking/withdraw",
    authMode: "SESSION",
    scope: "app.banking.write",
    idempotencyRequired: true,
    csrfRequired: true,
    integrityPolicy: "RISK_BASED",
    economyCommand: "post:banking.withdraw",
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/banking/withdraw",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/board/images/:key",
    authMode: "SESSION",
    scope: "app.board.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/board/images/:key",
  },
  {
    channel: "APP",
    method: "POST",
    pathTemplate: "/app-api/v2/board/images/uploads",
    authMode: "SESSION",
    scope: "app.board.write",
    idempotencyRequired: false,
    csrfRequired: true,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/board/images/uploads",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/board/posts",
    authMode: "SESSION",
    scope: "app.board.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/board/posts",
  },
  {
    channel: "APP",
    method: "POST",
    pathTemplate: "/app-api/v2/board/posts",
    authMode: "SESSION",
    scope: "app.board.write",
    idempotencyRequired: false,
    csrfRequired: true,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/board/posts",
  },
  {
    channel: "APP",
    method: "DELETE",
    pathTemplate: "/app-api/v2/board/posts/:id",
    authMode: "SESSION",
    scope: "app.board.write",
    idempotencyRequired: false,
    csrfRequired: true,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/board/posts/:id",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/board/posts/:id",
    authMode: "SESSION",
    scope: "app.board.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/board/posts/:id",
  },
  {
    channel: "APP",
    method: "PUT",
    pathTemplate: "/app-api/v2/board/posts/:id",
    authMode: "SESSION",
    scope: "app.board.write",
    idempotencyRequired: false,
    csrfRequired: true,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/board/posts/:id",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/board/posts/:id/comments",
    authMode: "SESSION",
    scope: "app.board.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/board/posts/:id/comments",
  },
  {
    channel: "APP",
    method: "POST",
    pathTemplate: "/app-api/v2/board/posts/:id/comments",
    authMode: "SESSION",
    scope: "app.board.write",
    idempotencyRequired: false,
    csrfRequired: true,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/board/posts/:id/comments",
  },
  {
    channel: "APP",
    method: "DELETE",
    pathTemplate: "/app-api/v2/board/posts/:id/comments/:commentId",
    authMode: "SESSION",
    scope: "app.board.write",
    idempotencyRequired: false,
    csrfRequired: true,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/board/posts/:id/comments/:commentId",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/board/public/images/:key",
    authMode: "PUBLIC",
    scope: "app.board.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/board/public/images/:key",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/board/public/posts",
    authMode: "PUBLIC",
    scope: "app.board.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/board/public/posts",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/board/public/posts/:id",
    authMode: "PUBLIC",
    scope: "app.board.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/board/public/posts/:id",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/board/public/posts/:id/comments",
    authMode: "PUBLIC",
    scope: "app.board.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/board/public/posts/:id/comments",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/board/public/stock-posts",
    authMode: "PUBLIC",
    scope: "app.board.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/board/public/stock-posts",
  },
  {
    channel: "APP",
    method: "POST",
    pathTemplate: "/app-api/v2/board/stock-posts",
    authMode: "SESSION",
    scope: "app.board.write",
    idempotencyRequired: false,
    csrfRequired: true,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/board/stock-posts",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/businesses",
    authMode: "SESSION",
    scope: "app.businesses.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/businesses",
  },
  {
    channel: "APP",
    method: "POST",
    pathTemplate: "/app-api/v2/businesses/:id/boost",
    authMode: "SESSION",
    scope: "app.businesses.write",
    idempotencyRequired: true,
    csrfRequired: true,
    integrityPolicy: "NONE",
    economyCommand: "post:businesses.{id}.boost",
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/businesses/:id/boost",
  },
  {
    channel: "APP",
    method: "POST",
    pathTemplate: "/app-api/v2/businesses/:id/settle-v2",
    authMode: "SESSION",
    scope: "app.businesses.write",
    idempotencyRequired: true,
    csrfRequired: true,
    integrityPolicy: "RISK_BASED",
    economyCommand: "post:businesses.{id}.settle-v2",
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/businesses/:id/settle-v2",
  },
  {
    channel: "APP",
    method: "POST",
    pathTemplate: "/app-api/v2/businesses/:id/settlements",
    authMode: "SESSION",
    scope: "app.businesses.write",
    idempotencyRequired: true,
    csrfRequired: true,
    integrityPolicy: "RISK_BASED",
    economyCommand: "post:businesses.{id}.settlements",
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/businesses/:id/settlements",
  },
  {
    channel: "APP",
    method: "POST",
    pathTemplate: "/app-api/v2/businesses/activate-license",
    authMode: "SESSION",
    scope: "app.businesses.write",
    idempotencyRequired: true,
    csrfRequired: true,
    integrityPolicy: "NONE",
    economyCommand: "post:businesses.activate-license",
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/businesses/activate-license",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/businesses/catalog",
    authMode: "SESSION",
    scope: "app.businesses.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/businesses/catalog",
  },
  {
    channel: "APP",
    method: "POST",
    pathTemplate: "/app-api/v2/businesses/catalog/:id/purchases",
    authMode: "SESSION",
    scope: "app.businesses.write",
    idempotencyRequired: true,
    csrfRequired: true,
    integrityPolicy: "RISK_BASED",
    economyCommand: "post:businesses.catalog.{id}.purchases",
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/businesses/catalog/:id/purchases",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/businesses/equity",
    authMode: "SESSION",
    scope: "app.businesses.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/businesses/equity",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/businesses/my-v2",
    authMode: "SESSION",
    scope: "app.businesses.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/businesses/my-v2",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/casino/coin/fairness",
    authMode: "SESSION",
    scope: "app.casino.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/casino/coin/fairness",
  },
  {
    channel: "APP",
    method: "POST",
    pathTemplate: "/app-api/v2/casino/coin/plays",
    authMode: "SESSION",
    scope: "app.casino.write",
    idempotencyRequired: true,
    csrfRequired: true,
    integrityPolicy: "NONE",
    economyCommand: "post:casino.coin.plays",
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/casino/coin/plays",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/casino/coin/terms",
    authMode: "SESSION",
    scope: "app.casino.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/casino/coin/terms",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/casino/dice/fairness",
    authMode: "SESSION",
    scope: "app.casino.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/casino/dice/fairness",
  },
  {
    channel: "APP",
    method: "POST",
    pathTemplate: "/app-api/v2/casino/dice/plays",
    authMode: "SESSION",
    scope: "app.casino.write",
    idempotencyRequired: true,
    csrfRequired: true,
    integrityPolicy: "NONE",
    economyCommand: "post:casino.dice.plays",
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/casino/dice/plays",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/casino/games/terms",
    authMode: "SESSION",
    scope: "app.casino.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/casino/games/terms",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/casino/history",
    authMode: "SESSION",
    scope: "app.casino.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/casino/history",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/casino/self-limit",
    authMode: "SESSION",
    scope: "app.casino.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/casino/self-limit",
  },
  {
    channel: "APP",
    method: "PUT",
    pathTemplate: "/app-api/v2/casino/self-limit",
    authMode: "SESSION",
    scope: "app.casino.write",
    idempotencyRequired: true,
    csrfRequired: true,
    integrityPolicy: "NONE",
    economyCommand: "put:casino.self-limit",
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/casino/self-limit",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/content/announcements",
    authMode: "PUBLIC",
    scope: "app.content.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/content/announcements",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/content/photos",
    authMode: "PUBLIC",
    scope: "app.content.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/content/photos",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/content/status",
    authMode: "PUBLIC",
    scope: "app.content.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/content/status",
  },
  {
    channel: "APP",
    method: "POST",
    pathTemplate: "/app-api/v2/early-game/claims",
    authMode: "SESSION",
    scope: "app.early-game.write",
    idempotencyRequired: true,
    csrfRequired: true,
    integrityPolicy: "NONE",
    economyCommand: "post:early-game.claims",
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/early-game/claims",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/early-game/first-day",
    authMode: "SESSION",
    scope: "app.early-game.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/early-game/first-day",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/early-game/today",
    authMode: "SESSION",
    scope: "app.early-game.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/early-game/today",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/engagement",
    authMode: "SESSION",
    scope: "app.engagement.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/engagement",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/engagement/early-game",
    authMode: "SESSION",
    scope: "app.engagement.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/engagement/early-game",
  },
  {
    channel: "APP",
    method: "POST",
    pathTemplate: "/app-api/v2/engagement/npcs/:code/orders",
    authMode: "SESSION",
    scope: "app.engagement.write",
    idempotencyRequired: true,
    csrfRequired: true,
    integrityPolicy: "NONE",
    economyCommand: "post:engagement.npcs.{code}.orders",
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/engagement/npcs/:code/orders",
  },
  {
    channel: "APP",
    method: "PUT",
    pathTemplate: "/app-api/v2/engagement/preferences",
    authMode: "SESSION",
    scope: "app.engagement.write",
    idempotencyRequired: true,
    csrfRequired: true,
    integrityPolicy: "NONE",
    economyCommand: "put:engagement.preferences",
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/engagement/preferences",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/game-clock",
    authMode: "PUBLIC",
    scope: "app.game-clock.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: true,
    availability: "TARGET",
    legacyPath: "/app-api/v1/game-clock",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/media/:key",
    authMode: "PUBLIC",
    scope: "app.media.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/media/:key",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/media/profile/:key",
    authMode: "PUBLIC",
    scope: "app.media.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/media/profile/:key",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/photos",
    authMode: "SESSION",
    scope: "app.photos.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/photos",
  },
  {
    channel: "APP",
    method: "POST",
    pathTemplate: "/app-api/v2/photos",
    authMode: "SESSION",
    scope: "app.photos.write",
    idempotencyRequired: false,
    csrfRequired: true,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/photos",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/photos/mine",
    authMode: "SESSION",
    scope: "app.photos.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/photos/mine",
  },
  {
    channel: "APP",
    method: "POST",
    pathTemplate: "/app-api/v2/photos/uploads",
    authMode: "SESSION",
    scope: "app.photos.write",
    idempotencyRequired: false,
    csrfRequired: true,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/photos/uploads",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/privacy/requests",
    authMode: "SESSION",
    scope: "app.privacy.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/privacy/requests",
  },
  {
    channel: "APP",
    method: "POST",
    pathTemplate: "/app-api/v2/privacy/requests",
    authMode: "SESSION",
    scope: "app.privacy.write",
    idempotencyRequired: false,
    csrfRequired: true,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/privacy/requests",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/profile",
    authMode: "SESSION",
    scope: "app.profile.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/profile",
  },
  {
    channel: "APP",
    method: "PUT",
    pathTemplate: "/app-api/v2/profile",
    authMode: "SESSION",
    scope: "app.profile.write",
    idempotencyRequired: false,
    csrfRequired: true,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/profile",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/profile/:userId",
    authMode: "SESSION",
    scope: "app.profile.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/profile/:userId",
  },
  {
    channel: "APP",
    method: "DELETE",
    pathTemplate: "/app-api/v2/profile/image",
    authMode: "SESSION",
    scope: "app.profile.write",
    idempotencyRequired: false,
    csrfRequired: true,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/profile/image",
  },
  {
    channel: "APP",
    method: "POST",
    pathTemplate: "/app-api/v2/profile/image",
    authMode: "SESSION",
    scope: "app.profile.write",
    idempotencyRequired: false,
    csrfRequired: true,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/profile/image",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/profile/settings",
    authMode: "SESSION",
    scope: "app.profile.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/profile/settings",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/profile/titles",
    authMode: "SESSION",
    scope: "app.profile.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/profile/titles",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/progression",
    authMode: "SESSION",
    scope: "app.progression.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/progression",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/progression/credit",
    authMode: "SESSION",
    scope: "app.progression.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/progression/credit",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/progression/early-game",
    authMode: "SESSION",
    scope: "app.progression.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/progression/early-game",
  },
  {
    channel: "APP",
    method: "POST",
    pathTemplate: "/app-api/v2/progression/refreshes",
    authMode: "SESSION",
    scope: "app.progression.write",
    idempotencyRequired: true,
    csrfRequired: true,
    integrityPolicy: "NONE",
    economyCommand: "post:progression.refreshes",
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/progression/refreshes",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/rewards/availability",
    authMode: "SESSION",
    scope: "app.rewards.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/rewards/availability",
  },
  {
    channel: "APP",
    method: "POST",
    pathTemplate: "/app-api/v2/rewards/daily/claims",
    authMode: "SESSION",
    scope: "app.rewards.write",
    idempotencyRequired: true,
    csrfRequired: true,
    integrityPolicy: "NONE",
    economyCommand: "post:rewards.daily.claims",
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/rewards/daily/claims",
  },
  {
    channel: "APP",
    method: "POST",
    pathTemplate: "/app-api/v2/rewards/work/claims",
    authMode: "SESSION",
    scope: "app.rewards.write",
    idempotencyRequired: true,
    csrfRequired: true,
    integrityPolicy: "NONE",
    economyCommand: "post:rewards.work.claims",
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/rewards/work/claims",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/seasons/events",
    authMode: "SESSION",
    scope: "app.seasons.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/seasons/events",
  },
  {
    channel: "APP",
    method: "POST",
    pathTemplate: "/app-api/v2/seasons/events/:id/consumptions",
    authMode: "SESSION",
    scope: "app.seasons.write",
    idempotencyRequired: true,
    csrfRequired: true,
    integrityPolicy: "NONE",
    economyCommand: "post:seasons.events.{id}.consumptions",
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/seasons/events/:id/consumptions",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/seasons/events/:id/leaderboard",
    authMode: "SESSION",
    scope: "app.seasons.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/seasons/events/:id/leaderboard",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/shop/catalog",
    authMode: "SESSION",
    scope: "app.shop.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/shop/catalog",
  },
  {
    channel: "APP",
    method: "POST",
    pathTemplate: "/app-api/v2/shop/catalog/:id/purchases",
    authMode: "SESSION",
    scope: "app.shop.write",
    idempotencyRequired: true,
    csrfRequired: true,
    integrityPolicy: "RISK_BASED",
    economyCommand: "post:shop.catalog.{id}.purchases",
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/shop/catalog/:id/purchases",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/shop/cosmetics/:userId",
    authMode: "SESSION",
    scope: "app.shop.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/shop/cosmetics/:userId",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/shop/holdings",
    authMode: "SESSION",
    scope: "app.shop.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/shop/holdings",
  },
  {
    channel: "APP",
    method: "POST",
    pathTemplate: "/app-api/v2/shop/holdings/:id/consumptions",
    authMode: "SESSION",
    scope: "app.shop.write",
    idempotencyRequired: true,
    csrfRequired: true,
    integrityPolicy: "NONE",
    economyCommand: "post:shop.holdings.{id}.consumptions",
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/shop/holdings/:id/consumptions",
  },
  {
    channel: "APP",
    method: "POST",
    pathTemplate: "/app-api/v2/shop/holdings/:id/equip",
    authMode: "SESSION",
    scope: "app.shop.write",
    idempotencyRequired: true,
    csrfRequired: true,
    integrityPolicy: "NONE",
    economyCommand: "post:shop.holdings.{id}.equip",
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/shop/holdings/:id/equip",
  },
  {
    channel: "APP",
    method: "POST",
    pathTemplate: "/app-api/v2/shop/holdings/:id/upkeep-settlements",
    authMode: "SESSION",
    scope: "app.shop.write",
    idempotencyRequired: true,
    csrfRequired: true,
    integrityPolicy: "NONE",
    economyCommand: "post:shop.holdings.{id}.upkeep-settlements",
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/shop/holdings/:id/upkeep-settlements",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/shop/items",
    authMode: "SESSION",
    scope: "app.shop.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/shop/items",
  },
  {
    channel: "APP",
    method: "POST",
    pathTemplate: "/app-api/v2/shop/items/:id/purchases",
    authMode: "SESSION",
    scope: "app.shop.write",
    idempotencyRequired: true,
    csrfRequired: true,
    integrityPolicy: "RISK_BASED",
    economyCommand: "post:shop.items.{id}.purchases",
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/shop/items/:id/purchases",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/shop/public-catalog",
    authMode: "PUBLIC",
    scope: "app.shop.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/shop/public-catalog",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/shop/purchases",
    authMode: "SESSION",
    scope: "app.shop.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/shop/purchases",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/stocks",
    authMode: "SESSION",
    scope: "app.stocks.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: true,
    availability: "TARGET",
    legacyPath: "/app-api/v1/stocks",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/stocks/:id/candles",
    authMode: "SESSION",
    scope: "app.stocks.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/stocks/:id/candles",
  },
  {
    channel: "APP",
    method: "POST",
    pathTemplate: "/app-api/v2/stocks/:id/orders",
    authMode: "SESSION",
    scope: "app.stocks.write",
    idempotencyRequired: true,
    csrfRequired: true,
    integrityPolicy: "RISK_BASED",
    economyCommand: "post:stocks.{id}.orders",
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/stocks/:id/orders",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/stocks/:id/prices",
    authMode: "SESSION",
    scope: "app.stocks.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/stocks/:id/prices",
  },
  {
    channel: "APP",
    method: "POST",
    pathTemplate: "/app-api/v2/stocks/:id/watchlist",
    authMode: "SESSION",
    scope: "app.stocks.write",
    idempotencyRequired: true,
    csrfRequired: true,
    integrityPolicy: "NONE",
    economyCommand: "post:stocks.{id}.watchlist",
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/stocks/:id/watchlist",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/stocks/alerts",
    authMode: "SESSION",
    scope: "app.stocks.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/stocks/alerts",
  },
  {
    channel: "APP",
    method: "POST",
    pathTemplate: "/app-api/v2/stocks/alerts",
    authMode: "SESSION",
    scope: "app.stocks.write",
    idempotencyRequired: true,
    csrfRequired: true,
    integrityPolicy: "NONE",
    economyCommand: "post:stocks.alerts",
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/stocks/alerts",
  },
  {
    channel: "APP",
    method: "DELETE",
    pathTemplate: "/app-api/v2/stocks/alerts/:id",
    authMode: "SESSION",
    scope: "app.stocks.write",
    idempotencyRequired: true,
    csrfRequired: true,
    integrityPolicy: "NONE",
    economyCommand: "delete:stocks.alerts.{id}",
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/stocks/alerts/:id",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/stocks/alerts/events",
    authMode: "SESSION",
    scope: "app.stocks.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/stocks/alerts/events",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/stocks/history",
    authMode: "SESSION",
    scope: "app.stocks.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/stocks/history",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/stocks/market-events",
    authMode: "SESSION",
    scope: "app.stocks.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/stocks/market-events",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/stocks/portfolio",
    authMode: "SESSION",
    scope: "app.stocks.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/stocks/portfolio",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/stocks/sparklines",
    authMode: "SESSION",
    scope: "app.stocks.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/stocks/sparklines",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/stocks/watchlist",
    authMode: "SESSION",
    scope: "app.stocks.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/stocks/watchlist",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/support/threads",
    authMode: "SESSION",
    scope: "app.support.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: true,
    availability: "TARGET",
    legacyPath: "/app-api/v1/support/threads",
  },
  {
    channel: "APP",
    method: "POST",
    pathTemplate: "/app-api/v2/support/threads",
    authMode: "SESSION",
    scope: "app.support.write",
    idempotencyRequired: false,
    csrfRequired: true,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/support/threads",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/support/threads/:id/messages",
    authMode: "SESSION",
    scope: "app.support.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: true,
    availability: "TARGET",
    legacyPath: "/app-api/v1/support/threads/:id/messages",
  },
  {
    channel: "APP",
    method: "POST",
    pathTemplate: "/app-api/v2/support/threads/:id/messages",
    authMode: "SESSION",
    scope: "app.support.write",
    idempotencyRequired: false,
    csrfRequired: true,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/support/threads/:id/messages",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/wallet",
    authMode: "SESSION",
    scope: "app.wallet.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/wallet",
  },
  {
    channel: "APP",
    method: "POST",
    pathTemplate: "/app-api/v2/wallet/transfers",
    authMode: "SESSION",
    scope: "app.wallet.write",
    idempotencyRequired: true,
    csrfRequired: true,
    integrityPolicy: "RISK_BASED",
    economyCommand: "post:wallet.transfers",
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/wallet/transfers",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/work",
    authMode: "SESSION",
    scope: "app.work.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/work",
  },
  {
    channel: "APP",
    method: "POST",
    pathTemplate: "/app-api/v2/work/active-job",
    authMode: "SESSION",
    scope: "app.work.write",
    idempotencyRequired: true,
    csrfRequired: true,
    integrityPolicy: "NONE",
    economyCommand: "post:work.active-job",
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/work/active-job",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/work/assignments",
    authMode: "SESSION",
    scope: "app.work.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/work/assignments",
  },
  {
    channel: "APP",
    method: "POST",
    pathTemplate: "/app-api/v2/work/assignments",
    authMode: "SESSION",
    scope: "app.work.write",
    idempotencyRequired: true,
    csrfRequired: true,
    integrityPolicy: "NONE",
    economyCommand: "post:work.assignments",
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/work/assignments",
  },
  {
    channel: "APP",
    method: "POST",
    pathTemplate: "/app-api/v2/work/assignments/:id/completions",
    authMode: "SESSION",
    scope: "app.work.write",
    idempotencyRequired: true,
    csrfRequired: true,
    integrityPolicy: "NONE",
    economyCommand: "post:work.assignments.{id}.completions",
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/work/assignments/:id/completions",
  },
  {
    channel: "APP",
    method: "POST",
    pathTemplate: "/app-api/v2/work/assignments/:id/verify",
    authMode: "SESSION",
    scope: "app.work.write",
    idempotencyRequired: true,
    csrfRequired: true,
    integrityPolicy: "NONE",
    economyCommand: "post:work.assignments.{id}.verify",
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/work/assignments/:id/verify",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/work/profile",
    authMode: "SESSION",
    scope: "app.work.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/work/profile",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/work/receipts",
    authMode: "SESSION",
    scope: "app.work.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/work/receipts",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/work/tasks",
    authMode: "SESSION",
    scope: "app.work.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/work/tasks",
  },
  {
    channel: "APP",
    method: "POST",
    pathTemplate: "/app-api/v2/work/tasks/:id/complete",
    authMode: "SESSION",
    scope: "app.work.write",
    idempotencyRequired: true,
    csrfRequired: true,
    integrityPolicy: "NONE",
    economyCommand: "post:work.tasks.{id}.complete",
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/work/tasks/:id/complete",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/newspaper/pulse",
    authMode: "PUBLIC",
    scope: "app.newspaper.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: true,
    availability: "TARGET",
    legacyPath: "/app-api/v1/newspaper/pulse",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/newspaper/poll",
    authMode: "PUBLIC",
    scope: "app.newspaper.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: true,
    availability: "TARGET",
    legacyPath: "/app-api/v1/newspaper/poll",
  },
  {
    channel: "APP",
    method: "POST",
    pathTemplate: "/app-api/v2/newspaper/poll/vote",
    authMode: "SESSION",
    scope: "app.newspaper.write",
    idempotencyRequired: false,
    csrfRequired: true,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/newspaper/poll/vote",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/newspaper/lore",
    authMode: "PUBLIC",
    scope: "app.newspaper.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: true,
    availability: "TARGET",
    legacyPath: "/app-api/v1/newspaper/lore",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/banking/pockets",
    authMode: "SESSION",
    scope: "app.banking.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/banking/pockets",
  },
  {
    channel: "APP",
    method: "POST",
    pathTemplate: "/app-api/v2/banking/pockets",
    authMode: "SESSION",
    scope: "app.banking.write",
    idempotencyRequired: true,
    csrfRequired: true,
    integrityPolicy: "NONE",
    economyCommand: "post:banking.pockets",
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/banking/pockets",
  },
  {
    channel: "APP",
    method: "POST",
    pathTemplate: "/app-api/v2/banking/pockets/:id/transfer",
    authMode: "SESSION",
    scope: "app.banking.write",
    idempotencyRequired: true,
    csrfRequired: true,
    integrityPolicy: "NONE",
    economyCommand: "post:banking.pockets.{id}.transfer",
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/banking/pockets/:id/transfer",
  },
  {
    channel: "APP",
    method: "PUT",
    pathTemplate: "/app-api/v2/banking/pockets/:id",
    authMode: "SESSION",
    scope: "app.banking.write",
    idempotencyRequired: true,
    csrfRequired: true,
    integrityPolicy: "NONE",
    economyCommand: "put:banking.pockets.{id}",
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/banking/pockets/:id",
  },
  {
    channel: "APP",
    method: "POST",
    pathTemplate: "/app-api/v2/banking/pockets/:id/archive",
    authMode: "SESSION",
    scope: "app.banking.write",
    idempotencyRequired: true,
    csrfRequired: true,
    integrityPolicy: "NONE",
    economyCommand: "post:banking.pockets.{id}.archive",
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/banking/pockets/:id/archive",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/crafting/recipes",
    authMode: "SESSION",
    scope: "app.crafting.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/crafting/recipes",
  },
  {
    channel: "APP",
    method: "POST",
    pathTemplate: "/app-api/v2/crafting/execute",
    authMode: "SESSION",
    scope: "app.crafting.write",
    idempotencyRequired: true,
    csrfRequired: true,
    integrityPolicy: "NONE",
    economyCommand: "post:crafting.execute",
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/crafting/execute",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/marketplace/listings",
    authMode: "SESSION",
    scope: "app.marketplace.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/marketplace/listings",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/marketplace/my-listings",
    authMode: "SESSION",
    scope: "app.marketplace.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/marketplace/my-listings",
  },
  {
    channel: "APP",
    method: "POST",
    pathTemplate: "/app-api/v2/marketplace/listings",
    authMode: "SESSION",
    scope: "app.marketplace.write",
    idempotencyRequired: true,
    csrfRequired: true,
    integrityPolicy: "RISK_BASED",
    economyCommand: "post:marketplace.listings",
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/marketplace/listings",
  },
  {
    channel: "APP",
    method: "POST",
    pathTemplate: "/app-api/v2/marketplace/listings/:id/buy",
    authMode: "SESSION",
    scope: "app.marketplace.write",
    idempotencyRequired: true,
    csrfRequired: true,
    integrityPolicy: "RISK_BASED",
    economyCommand: "post:marketplace.listings.{id}.buy",
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/marketplace/listings/:id/buy",
  },
  {
    channel: "APP",
    method: "POST",
    pathTemplate: "/app-api/v2/marketplace/listings/:id/cancel",
    authMode: "SESSION",
    scope: "app.marketplace.write",
    idempotencyRequired: true,
    csrfRequired: true,
    integrityPolicy: "RISK_BASED",
    economyCommand: "post:marketplace.listings.{id}.cancel",
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/marketplace/listings/:id/cancel",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/notifications",
    authMode: "SESSION",
    scope: "app.notifications.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/notifications",
  },
  {
    channel: "APP",
    method: "GET",
    pathTemplate: "/app-api/v2/notifications/unread-count",
    authMode: "SESSION",
    scope: "app.notifications.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/notifications/unread-count",
  },
  {
    channel: "APP",
    method: "POST",
    pathTemplate: "/app-api/v2/notifications/:id/read",
    authMode: "SESSION",
    scope: "app.notifications.write",
    idempotencyRequired: false,
    csrfRequired: true,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/notifications/:id/read",
  },
  {
    channel: "APP",
    method: "POST",
    pathTemplate: "/app-api/v2/notifications/read-all",
    authMode: "SESSION",
    scope: "app.notifications.write",
    idempotencyRequired: false,
    csrfRequired: true,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/notifications/read-all",
  },
  {
    channel: "SITE",
    method: "GET",
    pathTemplate: "/site-api/v1/auth/session",
    authMode: "SESSION",
    scope: "site.auth.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: true,
    availability: "TARGET",
    legacyPath: "/app-api/v1/auth/session",
  },
  {
    channel: "SITE",
    method: "GET",
    pathTemplate: "/site-api/v1/support/threads",
    authMode: "SESSION",
    scope: "site.support.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: true,
    availability: "TARGET",
    legacyPath: "/app-api/v1/support/threads",
  },
  {
    channel: "SITE",
    method: "POST",
    pathTemplate: "/site-api/v1/support/threads",
    authMode: "SESSION",
    scope: "site.support.write",
    idempotencyRequired: true,
    csrfRequired: true,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/support/threads",
  },
  {
    channel: "SITE",
    method: "GET",
    pathTemplate: "/site-api/v1/support/threads/:id/messages",
    authMode: "SESSION",
    scope: "site.support.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: true,
    availability: "TARGET",
    legacyPath: "/app-api/v1/support/threads/:id/messages",
  },
  {
    channel: "SITE",
    method: "POST",
    pathTemplate: "/site-api/v1/support/threads/:id/messages",
    authMode: "SESSION",
    scope: "site.support.write",
    idempotencyRequired: true,
    csrfRequired: true,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/support/threads/:id/messages",
  },
  {
    channel: "SITE",
    method: "GET",
    pathTemplate: "/site-api/v1/chat/conversations",
    authMode: "SESSION",
    scope: "site.chat.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/chat/conversations",
  },
  {
    channel: "SITE",
    method: "GET",
    pathTemplate: "/site-api/v1/chat/conversations/:id/messages",
    authMode: "SESSION",
    scope: "site.chat.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/chat/conversations/:id/messages",
  },
  {
    channel: "SITE",
    method: "POST",
    pathTemplate: "/site-api/v1/chat/conversations/:id/messages",
    authMode: "SESSION",
    scope: "site.chat.write",
    idempotencyRequired: true,
    csrfRequired: true,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/chat/conversations/:id/messages",
  },
  {
    channel: "SITE",
    method: "GET",
    pathTemplate: "/site-api/v1/chat/conversations/:id/sync",
    authMode: "SESSION",
    scope: "site.chat.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/chat/conversations/:id/sync",
  },
  {
    channel: "SITE",
    method: "POST",
    pathTemplate: "/site-api/v1/chat/conversations/:id/read",
    authMode: "SESSION",
    scope: "site.chat.write",
    idempotencyRequired: true,
    csrfRequired: true,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/chat/conversations/:id/read",
  },
  {
    channel: "SITE",
    method: "GET",
    pathTemplate: "/site-api/v1/chat/unread-count",
    authMode: "SESSION",
    scope: "site.chat.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/chat/unread-count",
  },
  {
    channel: "SITE",
    method: "GET",
    pathTemplate: "/site-api/v1/game-clock",
    authMode: "PUBLIC",
    scope: "site.game-clock.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: true,
    availability: "TARGET",
    legacyPath: "/app-api/v1/game-clock",
  },
  {
    channel: "SITE",
    method: "GET",
    pathTemplate: "/site-api/v1/engagement/dopamine/status",
    authMode: "SESSION",
    scope: "site.engagement.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/engagement/dopamine/status",
  },
  {
    channel: "SITE",
    method: "POST",
    pathTemplate: "/site-api/v1/engagement/dopamine/golden-duck",
    authMode: "SESSION",
    scope: "site.engagement.write",
    idempotencyRequired: true,
    csrfRequired: true,
    integrityPolicy: "NONE",
    economyCommand: "post:engagement.dopamine.golden-duck",
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/engagement/dopamine/golden-duck",
  },
  {
    channel: "SITE",
    method: "POST",
    pathTemplate: "/site-api/v1/engagement/dopamine/pet-fortune",
    authMode: "SESSION",
    scope: "site.engagement.write",
    idempotencyRequired: true,
    csrfRequired: true,
    integrityPolicy: "NONE",
    economyCommand: "post:engagement.dopamine.pet-fortune",
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/engagement/dopamine/pet-fortune",
  },
  {
    channel: "SITE",
    method: "POST",
    pathTemplate: "/site-api/v1/engagement/dopamine/bull-bear-vote",
    authMode: "SESSION",
    scope: "site.engagement.write",
    idempotencyRequired: true,
    csrfRequired: true,
    integrityPolicy: "NONE",
    economyCommand: "post:engagement.dopamine.bull-bear-vote",
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/engagement/dopamine/bull-bear-vote",
  },
  {
    channel: "SITE",
    method: "POST",
    pathTemplate: "/site-api/v1/engagement/dopamine/mini-showdown",
    authMode: "SESSION",
    scope: "site.engagement.write",
    idempotencyRequired: true,
    csrfRequired: true,
    integrityPolicy: "NONE",
    economyCommand: "post:engagement.dopamine.mini-showdown",
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/engagement/dopamine/mini-showdown",
  },
  {
    channel: "SITE",
    method: "POST",
    pathTemplate: "/site-api/v1/engagement/dopamine/star-drop",
    authMode: "SESSION",
    scope: "site.engagement.write",
    idempotencyRequired: true,
    csrfRequired: true,
    integrityPolicy: "NONE",
    economyCommand: "post:engagement.dopamine.star-drop",
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/engagement/dopamine/star-drop",
  },
  {
    channel: "SITE",
    method: "GET",
    pathTemplate: "/site-api/v1/newspaper/pulse",
    authMode: "PUBLIC",
    scope: "site.newspaper.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: true,
    availability: "TARGET",
    legacyPath: "/app-api/v1/newspaper/pulse",
  },
  {
    channel: "SITE",
    method: "GET",
    pathTemplate: "/site-api/v1/newspaper/poll",
    authMode: "PUBLIC",
    scope: "site.newspaper.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: true,
    availability: "TARGET",
    legacyPath: "/app-api/v1/newspaper/poll",
  },
  {
    channel: "SITE",
    method: "POST",
    pathTemplate: "/site-api/v1/newspaper/poll/vote",
    authMode: "SESSION",
    scope: "site.newspaper.write",
    idempotencyRequired: false,
    csrfRequired: true,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: false,
    availability: "TARGET",
    legacyPath: "/app-api/v1/newspaper/poll/vote",
  },
  {
    channel: "SITE",
    method: "GET",
    pathTemplate: "/site-api/v1/newspaper/lore",
    authMode: "PUBLIC",
    scope: "site.newspaper.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: true,
    availability: "TARGET",
    legacyPath: "/app-api/v1/newspaper/lore",
  },
  {
    channel: "SITE",
    method: "GET",
    pathTemplate: "/site-api/v1/stocks",
    authMode: "SESSION",
    scope: "site.stocks.read",
    idempotencyRequired: false,
    csrfRequired: false,
    integrityPolicy: "NONE",
    economyCommand: null,
    sharedReadOnly: true,
    availability: "TARGET",
    legacyPath: "/app-api/v1/stocks",
  },
] as const;

function pathMatches(template: string, pathname: string): boolean {
  const expected = template.split('/').filter(Boolean);
  const actual = pathname.split('/').filter(Boolean);
  if (expected.length !== actual.length) return false;
  return expected.every((segment, index) => segment.startsWith(':') || segment === actual[index]);
}

export function matchChannelRoute(
  channel: ApiChannel,
  method: string,
  path: string,
): ChannelRouteDefinition | null {
  const normalizedMethod = method.toUpperCase();
  const pathname = path.split('?', 1)[0] ?? path;
  return CHANNEL_API_ROUTES.find((route) =>
    route.channel === channel &&
    route.method === normalizedMethod &&
    pathMatches(route.pathTemplate, pathname)
  ) ?? null;
}
