import { existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { ROUTE_MAP } from '@moneyverse/contract';
import { describe, expect, it } from 'vitest';

/**
 * The route map claims a replacement for every route the original served.
 * The backend half is proved by requesting each one against the real Nest
 * application graph; this is the other half.
 *
 * It checks that a file exists to serve each path rather than rendering it,
 * because rendering needs a running API and a database — and the failure this
 * guards against is a row in the map with nothing behind it, which a file
 * check catches exactly.
 */
const APP = path.join(path.dirname(fileURLToPath(import.meta.url)), 'app');

function segments(routePath: string): string {
  return routePath
    .split('/')
    .filter((segment) => segment !== '')
    // `{key}` in the map is `[key]` on disk.
    .map((segment) => (segment.startsWith('{') ? `[${segment.slice(1, -1)}]` : segment))
    .join('/');
}

function servedBy(routePath: string): string | null {
  const directory = path.join(APP, segments(routePath));
  for (const candidate of ['page.tsx', 'route.ts']) {
    const file = path.join(directory, candidate);
    if (existsSync(file)) return file;
  }
  // robots.txt and sitemap.xml are generated by app/robots.ts and
  // app/sitemap.ts, whose file names drop the extension.
  const generated = path.join(APP, `${segments(routePath).replace(/\.[a-z]+$/, '')}.ts`);
  return existsSync(generated) ? generated : null;
}

const FRONTEND_ROUTES = ROUTE_MAP.filter(
  (mapping) => mapping.module === 'frontend' && mapping.replacement !== null,
).map((mapping) => (mapping.replacement as string).split(' ')[1] as string);

describe('every mapped frontend route is served', () => {
  it('has frontend routes to check', () => {
    expect(FRONTEND_ROUTES.length).toBeGreaterThan(15);
  });

  it.each(FRONTEND_ROUTES)('%s', (routePath) => {
    expect(servedBy(routePath), `${routePath} is in the route map but no file serves it`).not.toBe(
      null,
    );
  });
});
